Repository wildfly-security/wildfly-elytron, pull requests merged in 2018-07, with the labels that each got.

#1146 [ELY-1591] Provide Elytron alternative to RoleMappingLoginModule
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/authz/MappedRoleMapper.java
  src/main/java/org/wildfly/security/authz/MappedRoles.java
  src/test/java/org/wildfly/security/authz/RoleMappingTest.java
Labels: +1 DAL, +1 HK, Feature Request

#1018 [ELY-1418] CLIENT_CERT without certificates in security realm
  src/main/java/org/wildfly/security/http/HttpConstants.java
  src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java
  src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java
Labels: +1 DAL, +1 FJ, Feature Request

#1160 [ELY-1607] Revise cipher suites exposed by Elytron
  src/main/java/org/wildfly/security/ssl/Encryption.java
  src/main/java/org/wildfly/security/ssl/MechanismDatabase.properties
Labels: +1 DAL, +1 FJ

#1156 [ELY-1493] KeyStore test - extended too short timeouts more
  src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
Labels: +1 DAL, +1 FJ

#1148 [ELY-1573] equals/hashCode methods for PasswordSpec classes
  src/main/java/org/wildfly/security/password/spec/ClearPasswordSpec.java
  src/main/java/org/wildfly/security/password/spec/DigestPasswordSpec.java
  src/main/java/org/wildfly/security/password/spec/EncryptablePasswordSpec.java
  src/main/java/org/wildfly/security/password/spec/HashPasswordSpec.java
  src/main/java/org/wildfly/security/password/spec/IteratedHashPasswordSpec.java
  src/main/java/org/wildfly/security/password/spec/IteratedSaltedHashPasswordSpec.java
  src/main/java/org/wildfly/security/password/spec/MaskedPasswordSpec.java
  src/main/java/org/wildfly/security/password/spec/OneTimePasswordSpec.java
  src/main/java/org/wildfly/security/password/spec/SaltedHashPasswordSpec.java
Labels: +1 DAL, +1 DML

#1155 [ELY-1599] support of username* into Digest HTTP mechanism
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/http/HttpConstants.java
  src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java
  src/test/java/org/wildfly/security/http/DigestAuthenticationMechanismTest.java
Labels: +1 DAL, +1 FJ

#1153 [ELY-1601] SecurityIdentity.withSecurityIdentity null handling + tests
  src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
  src/test/java/org/wildfly/security/auth/server/IdentityPropagationTest.java
  src/test/java/org/wildfly/security/auth/server/IdentitySwitchingTest.java
Labels: +1 DAL, +1 FJ

#1152 [ELY-1531] runAs operations sync between Scoped/SecurityIdentity and AC
  src/main/java/org/wildfly/security/auth/client/AuthenticationContext.java
  src/main/java/org/wildfly/security/auth/server/FlexibleIdentityAssociation.java
  src/main/java/org/wildfly/security/auth/server/Scoped.java
  src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
Labels: +1 DAL, +1 FJ

#1147 [ELY-1287] Scope.SSL_SESSION into CLIENT_CERT instead of SSLSession
  src/main/java/org/wildfly/security/cache/CachedIdentity.java
  src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java
  src/main/java/org/wildfly/security/mechanism/_private/MechanismUtil.java
Labels: +1 DAL, +1 FJ

#1150 [ELY-1596] javadoc: required permissions for enabled security manager
  src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java
  src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
  src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
  src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
  src/main/java/org/wildfly/security/manager/StackInspector.java
  src/test/java/org/wildfly/security/sasl/test/StringPrepTest.java
  src/test/java/org/wildfly/security/util/Base32Test.java
  src/test/java/org/wildfly/security/util/Base64Test.java
Labels: +1 DAL, +1 FJ

#1159 [ELY-1604] Implement the client side of Let's Encrypt's Automatic Certificate Management Environment (ACME) protocol
  pom.xml
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/x500/cert/CertUtil.java
  src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java
  src/main/java/org/wildfly/security/x500/cert/SelfSignedX509CertificateAndSigningKey.java
  src/main/java/org/wildfly/security/x500/cert/X509CertificateBuilder.java
  src/main/java/org/wildfly/security/x500/cert/X509CertificateChainAndSigningKey.java
  src/main/java/org/wildfly/security/x500/cert/acme/Acme.java
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeAccount.java
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeChallenge.java
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeException.java
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeMetadata.java
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeResource.java
  src/main/java/org/wildfly/security/x500/cert/util/KeyUtil.java
  src/main/java/org/wildfly/security/x500/cert/util/package-info.java
  src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
  src/test/resources/org/wildfly/security/x500/cert/acme/account.keystore
  src/test/resources/org/wildfly/security/x500/cert/acme/readme.txt
Labels: +1 DAL, +1 HK, Feature Request

#1158 [ELY-1605] ELY05016: Unrecognized token for CCM mode cipher suites
  src/main/java/org/wildfly/security/ssl/Encryption.java
  src/main/java/org/wildfly/security/ssl/MechanismDatabase.properties
Labels: +1 FJ, +1 HK

#1164 [ELY-1618] Make Protocol.forName() case insensitive to allow TLS to work properly when using the Bouncy Castle JSSE provider
  src/main/java/org/wildfly/security/ssl/Protocol.java
Labels: +1 DAL, +1 HK
