Repository wildfly-security/wildfly-elytron, pull requests merged in 2018-09, with the labels that each got.

#1186 [ELY-1652] Remove generation time metadata from Javadoc
  pom.xml
Labels: +1 DAL, +1 FJ

#1183 [ELY-1640] No longer send the newKey in the inner payload for a key change request
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
  src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
Labels: +1 DAL, +1 HK, 1.6.x

#1190 [ELY-1664] Fix trace logging in SSLUtils
  src/main/java/org/wildfly/security/ssl/SSLUtils.java
Labels: +1 FJ, +1 HK, 1.6.x

#1176 [ELY-1637] Change ReferralMode.toString to return value
  src/main/java/org/wildfly/security/auth/realm/ldap/DirContextFactory.java
Labels: +1 DAL, +1 HK

#1187 [ELY-793] Using @STRENGTH keyword in CipherSuiteSelector.fromString should cause descending sorting
  src/main/java/org/wildfly/security/ssl/CipherSuiteSelector.java
  src/test/java/org/wildfly/security/ssl/CipherSuiteSelectorTest.java
Labels: +1 DAL, +1 FJ

#1174 [ELY-1634] LDAPS referrals broken
  src/main/java/org/wildfly/security/auth/realm/ldap/DelegatingLdapContext.java
Labels: +1 FJ, +1 HK

#1184 [ELY-1595] Reenabling source compatibility check
  pom.xml
Labels: +1 DAL, +1 FJ

#1197 [ELY-1535] [ELY-1613] [ELY-1672] [ELY-1673] [ELY-1674] Mechanism Database Fixes
  src/main/java/org/wildfly/security/ssl/Digest.java
  src/main/java/org/wildfly/security/ssl/Encryption.java
  src/main/java/org/wildfly/security/ssl/MechanismDatabase.properties
Labels: +1 DAL, +1 FJ

#1198 [ELY-1676] Add missing ARIA encryption to CipherSuiteSelector
  src/main/java/org/wildfly/security/ssl/CipherSuiteSelector.java
Labels: +1 DAL

#1199 [ELY-1678] Avoid NPE in AcmeClientSpi#checkContentType() when the content type is null and try to fix intermittent failures in AcmeClientSpiTest
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
  src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
Labels: +1 DAL

#1202 [ELY-1681] Include the thrown exception in the trace logging in SSLUtils#createSslContextFactory
  src/main/java/org/wildfly/security/ssl/SSLUtils.java
Labels: +1 DAL

#1203 [ELY-1683] Add more trace logging in SSLUtils#createSslContextFactory to indicate which protocols and providers are attempted
  src/main/java/org/wildfly/security/ssl/SSLUtils.java
Labels: +1 DAL

#1170 [ELY-1425] JASPI Implementation
  pom.xml
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/auth/jaspi/DelegatingAuthConfigFactory.java
  src/main/java/org/wildfly/security/auth/jaspi/ElytronAuthConfigFactory.java
  src/main/java/org/wildfly/security/auth/jaspi/Flag.java
  src/main/java/org/wildfly/security/auth/jaspi/JaspiConfigurationBuilder.java
  src/main/java/org/wildfly/security/auth/jaspi/impl/AuthenticationModuleDefinition.java
  src/main/java/org/wildfly/security/auth/jaspi/impl/ElytronAuthConfigProvider.java
  src/main/java/org/wildfly/security/auth/jaspi/impl/ElytronMessageInfo.java
  src/main/java/org/wildfly/security/auth/jaspi/impl/ElytronServerAuthConfig.java
  src/main/java/org/wildfly/security/auth/jaspi/impl/ElytronServerAuthContext.java
  src/main/java/org/wildfly/security/auth/jaspi/impl/JaspiAuthenticationContext.java
  src/main/java/org/wildfly/security/auth/jaspi/impl/SecurityActions.java
  src/main/java/org/wildfly/security/auth/jaspi/impl/ServletMessageInfo.java
  src/main/java/org/wildfly/security/auth/jaspi/impl/package-info.java
  src/main/java/org/wildfly/security/auth/jaspi/package-info.java
  src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
  src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
  src/main/java/org/wildfly/security/permission/ElytronPermission.java
  src/test/java/org/wildfly/security/auth/jaspi/AuthModuleBase.java
  src/test/java/org/wildfly/security/auth/jaspi/AuthModuleSecureTest.java
  src/test/java/org/wildfly/security/auth/jaspi/AuthModuleValidateTest.java
  src/test/java/org/wildfly/security/auth/jaspi/ElytronAuthConfigFactoryTest.java
  src/test/java/org/wildfly/security/auth/jaspi/JaspiAuthenticationContextTest.java
  src/test/java/org/wildfly/security/auth/jaspi/TestAuthConfigProvider.java
  src/test/java/org/wildfly/security/auth/jaspi/TestServerAuthModule.java
Labels: +1 FJ, Feature Request
