Repository wildfly-security/wildfly-elytron, pull requests merged in 2018-06, with the labels that each got.

#1149 [ELY-1570] handling null classloader in WildFlyElytronProvider
  src/main/java/org/wildfly/security/WildFlyElytronProvider.java
  src/test/java/org/wildfly/security/sasl/gssapi/CommunicationSuiteChild.java
Labels: +1 DAL, +1 DML

#1154 [ELY-1602] Temporarily add a Pem.generatePemX509Certificate() method that takes the ByteStringBuilder from Elytron as a parameter
  src/main/java/org/wildfly/security/pem/Pem.java
Labels: +1 DAL, +1 HK

#1151 [ELY-1586] Update test suite to use certificate generation utilities
  pom.xml
  src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
  src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
  src/test/java/org/wildfly/security/keystore/FilteringKeyStoreTest.java
  src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java
  src/test/java/org/wildfly/security/sasl/entity/EntityTest.java
  src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
  src/test/java/org/wildfly/security/util/PemTest.java
  src/test/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequestTest.java
  src/test/resources/ca/cacert.pem
  src/test/resources/ca/certs/01.pem
  src/test/resources/ca/certs/02.pem
  src/test/resources/ca/certs/03.pem
  src/test/resources/ca/certs/04.pem
  src/test/resources/ca/certs/05.pem
  src/test/resources/ca/certs/06.pem
  src/test/resources/ca/crl/blank.pem
  src/test/resources/ca/crl/firefly-revoked.pem
  src/test/resources/ca/crl/ica-revoked.pem
  src/test/resources/ca/jks/beetles.keystore
  src/test/resources/ca/jks/ca.truststore
  src/test/resources/ca/jks/dung.keystore
  src/test/resources/ca/jks/firefly.keystore
  src/test/resources/ca/jks/ladybird.keystore
  src/test/resources/ca/jks/localhost.keystore
  src/test/resources/ca/jks/scarab.keystore
  src/test/resources/ca/private/cakey.pem
  src/test/resources/client.truststore
  src/test/resources/ica/certs/00.pem
  src/test/resources/ica/crl/blank-blank.pem
  src/test/resources/ica/crl/blank.pem
  src/test/resources/ica/ica-chain.pem
  src/test/resources/ica/ica.csr.pem
  src/test/resources/ica/icacert.pem
  src/test/resources/ica/jks/rove.keystore
  src/test/resources/ica/jks/shortwinged.keystore
  src/test/resources/ica/private/icakey.pem
  src/test/resources/ldap/elytron-x509-verification.ldif
  src/test/resources/org/wildfly/security/keystore/filtered.keystore
  src/test/resources/server.keystore
  src/test/resources/server.truststore
  src/test/resources/wrong.keystore
Labels: +1 DAL, +1 FJ, +1 HK

#1157 [ELY-1603] Add missing HTTP mechanisms to the WildFlyElytronProvider initialisation.
  src/main/java/org/wildfly/security/WildFlyElytronProvider.java
Labels: +1 FJ, +1 HK
