Repository wildfly-security/wildfly-elytron, pull requests merged in 2018-04, with the labels that each got.

#1119 [ELY-1553] Wrap WildFlyElytronProvider construction in a privileged block
  src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
Labels: +1 DML, +1 HK

#1122 [ELY-1557] ElytronXMLParser use == comparison for strings
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
Labels: +1 DML, +1 FJ

#1117 [ELY-1550] FileAuditEndpoint - independent flush/sync
  src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java
Labels: +1 DAL, +1 FJ

#1133 Version bump to 1.4.0 and Updated README.md
  README.md
  pom.xml
Labels: +1 FJ, +1 HK, 1.4.x
