Repository wildfly-security/wildfly-elytron, pull requests merged in 2018-10, with the labels that each got.

#1205 [ELY-1671] Fix to build javadoc on JDK 10 and JDK 11
  pom.xml
Labels: +1 DAL

#1207 [ELY-1692] Tests are not run with -Djava8.home java
  pom.xml
  src/test/java/org/wildfly/security/ldap/X509EvidenceVerificationSuiteChild.java
Labels: +1 DAL, +1 FJ

#1210 [ELY-1697] Ensure CompatibilityClientTest removes the credential store file it creates
  src/test/java/org/wildfly/security/sasl/digest/CompatibilityClientTest.java
Labels: +1 DAL

#1166 [ELY-1551] JwtValidator jku and kid header parameters
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/auth/realm/token/validator/JwkManager.java
  src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
  src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLSocket.java
  src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
  src/test/java/org/wildfly/security/auth/realm/token/RsaJwk.java
  src/test/resources/org/wildfly/security/auth/realm/token/wildfly-jwt-test-config.xml
Labels: +1 FJ, Feature Request

#1209 [ELY-1698] Add profile for skipping default-tests
  pom.xml
Labels: +1 DAL

#1212 [ELY-1680] IBM, failing KeyStoreSuiteChild.testGetCertificateChainBinary
  src/test/java/org/wildfly/security/ldap/KeyStoreSuiteChild.java
  src/test/resources/ldap/elytron-keystore-tests.ldif
Labels: +1 DAL, +1 FJ
