Repository wildfly-security/wildfly-elytron, pull requests merged in 2018-03, with the labels that each got.

#1102 1.2.x [ELY-1533] Prevent SNAPSHOT versions of json-smart from being downloaded when building Elytron
  pom.xml
Labels: +1 DML, +1 HK, 1.2.x

#1103 [ELY-1533] Prevent SNAPSHOT versions of json-smart from being downloaded when building Elytron
  pom.xml
Labels: +1 DML, +1 HK

#1105 [ELY-1523] JAPICMP checking level independent on version number
  pom.xml
Labels: +1 DAL, +1 FJ

#1107 [ELY-1430] WARN logged during server shutdown when Elytron JACC is set
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/authz/jacc/JaccDelegatingPolicy.java
Labels: +1 FJ, +1 HK, 1.1.x

#1064 [ELY-1428] Ensure all calls to PasswordFactory.getInstance pass in a …
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
  src/test/resources/org/wildfly/security/auth/client/test-wildfly-config.xml
Labels: +1 FJ, +1 HK, 1.1.x

#1106 [ELY-1523] JAPICMP checking level independent on version number
  pom.xml
Labels: +1 DML, +1 FJ

#1114 [ELY-1533] Prevent SNAPSHOT versions of json-smart from being downloaded when building Elytron
  pom.xml
Labels: +1 FJ, +1 HK, 1.1.x

#1113 [ELY-1490] Use supported hash algorithm in DER encoder test DSA section
  src/test/java/org/wildfly/security/asn1/DEREncoderTest.java
Labels: +1 FJ, +1 HK, 1.1.x

#1111 [ELY-1503] Wrap the GSSContext and KerberosTicket to work with distributed session
  src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
Labels: +1 DML, +1 FJ, 1.1.x, Critical

#1115 [ELY-1436] Log jdbc-realm key-mapper processing
  src/main/java/org/wildfly/security/auth/realm/jdbc/mapper/PasswordKeyMapper.java
Labels: +1 FJ, +1 HK
