Repository wildfly-security/wildfly-elytron, pull requests merged in 2018-02, with the labels that each got.

#1087 [ELY-1507] JwtValidator issuer and audience check ignoring does not work
  src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
Labels: +1 DAL, +1 HK

#1090 [ELY-1509] Javadoc fixes
  src/main/java/org/wildfly/security/credential/store/CredentialStorePermission.java
  src/main/java/org/wildfly/security/manager/WildFlySecurityManagerPermission.java
  src/main/java/org/wildfly/security/permission/ElytronPermission.java
  src/main/java/org/wildfly/security/sasl/util/SortedMechanismClientServerFactory.java
  src/main/java/org/wildfly/security/sasl/util/SortedMechanismSaslServerFactory.java
  src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
Labels: +1 DAL, +1 FJ

#1086 [ELY-261] UsernamePasswordHashUtil deprecated
  pom.xml
  src/main/java/org/wildfly/security/_private/Main.java
  src/main/java/org/wildfly/security/sasl/util/UsernamePasswordHashUtil.java
  src/test/java/org/wildfly/security/sasl/digest/DigestCallbackHandlerUtils.java
  src/test/java/org/wildfly/security/sasl/test/UsernamePasswordHashUtilTest.java
Labels: +1 DAL, +1 FJ

#1081 [ELY-1494] disabled PKCS12 KeyStore test for HP, removed unnecessary workaround
  src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
Labels: +1 DAL, +1 FJ

#1059 [ELY-1405] The password attribute of resource owner credentials shoul…
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  src/main/resources/schema/elytron-client-1_1.xsd
  src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientV10Test.java
  src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientV11Test.java
  src/test/resources/org/wildfly/security/sasl/oauth2/wildfly-oauth2-test-config-v1_0.xml
  src/test/resources/org/wildfly/security/sasl/oauth2/wildfly-oauth2-test-config-v1_1.xml
Labels: +1 DAL, +1 PI

#1092 [ELY-1398] Add support for public API compatibility check using japicmp
  pom.xml
Labels: +1 FJ, +1 HK, Critical

#1085 [ELY-1479] Coverity, Missing call to superclass in AbstractGssapiMechanism
  src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
  src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java
Labels: +1 DAL, +1 HK

#1095 [ELY-1515] Update JAPICMP Check version to 1.2.0.Final and update includes to match latest public packages.
  pom.xml
Labels: +1 FJ, +1 HK

#1096 1.2.x [ELY-1515] Update JAPICMP Check version to 1.2.0.Final and update includes to match latest public packages.
  pom.xml
Labels: +1 FJ, +1 HK, 1.2.x

#1097 [ELY-1503] Ensure the reference to the GssContext and KerberosTicket can be dropped during Serialization.
  src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
Labels: +1 FJ, +1 HK

#1098 [ELY-1503] Ensure the reference to the GssContext and KerberosTicket can be dropped during Serialization.
  src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
Labels: +1 FJ, +1 HK, 1.2.x

#1094 [ELY-1510] Bearer authentication sends 401 to unprotected resources w…
  src/main/java/org/wildfly/security/http/impl/BearerTokenAuthenticationMechanism.java
Labels: +1 DAL, +1 FJ

#1073 [ELY-1082] Documentation is missing in elytron-1_0.xsd
  src/main/resources/schema/elytron-client-1_1.xsd
Labels: +1 HK, request for comments

#1099 1.2.x [ELY-1526] Update the default provider supplier to be an aggregate of the WildFlyElytronProvider plus the installed providers in order to ensure the WildFlyElytronProvider comes first
  src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
Labels: +1 DML, +1 SG, 1.2.x, Critical

#1100 [ELY-1526] Update the default provider supplier to be an aggregate of the WildFlyElytronProvider plus the installed providers in order to ensure the WildFlyElytronProvider comes first
  src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
Labels: +1 DML, +1 HK

#1101 1.2.x [ELY-1526] Add back the ability for security providers to be loaded using the service loader mechanism but ensure that we skip any provider that is already an installed provider
  src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  src/main/java/org/wildfly/security/util/ProviderServiceLoaderSupplier.java
  src/main/java/org/wildfly/security/util/ServiceLoaderSupplier.java
Labels: +1 DML, +1 HK, 1.2.x, Critical
