Repository wildfly-security/wildfly-elytron, pull requests merged in 2018-08, with the labels that each got.

#1162 Modified index to be a table
  index.html
Labels: +1 HK

#1165 [ELY-1618] Avoid NPE in Protocol.forName() when the protocol name is null
  src/main/java/org/wildfly/security/ssl/Protocol.java
Labels: +1 DAL, +1 HK

#1167 [ELY-1625] Fix ECPublicKey import
  src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
Labels: +1 DAL, +1 HK

#1168 [ELY-1622] Ensure ConfigurationKeyManager.Builder gets used even when no key-store-ssl-certificate is specified
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
Labels: +1 DAL, +1 HK

#1163 [ELY-1616] ldap-key-store requires attribute userPKCS12 on ldap entry…
  src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordCredentialLoader.java
  src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
  src/main/java/org/wildfly/security/keystore/LdapKeyStoreSpi.java
  src/main/java/org/wildfly/security/util/LdapUtil.java
  src/test/java/org/wildfly/security/ldap/KeyStoreSuiteChild.java
  src/test/java/org/wildfly/security/ldap/PasswordSupportSuiteChild.java
  src/test/java/org/wildfly/security/ldap/X509EvidenceVerificationSuiteChild.java
  src/test/resources/ldap/elytron-credential-tests.ldif
  src/test/resources/ldap/elytron-keystore-tests.ldif
  src/test/resources/ldap/elytron-x509-verification.ldif
Labels: +1 FJ, +1 HK, 1.1.x

#1171 [ELY-1630] Ensure that any blank lines in the PEM certificate chain returned by an ACME server get ignored to avoid parsing issues on IBM JDK
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
Labels: +1 DAL, +1 HK

#1173 [ELY-1633] Incorrect double checked locking in AuthenticationConfiguration
  src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
Labels: +1 DAL, +1 FJ

#1172 [ELY-1632] Fix compiler warnings
  src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
  src/main/java/org/wildfly/security/cache/LRURealmIdentityCache.java
  src/main/java/org/wildfly/security/http/impl/NonceManager.java
  src/test/java/org/wildfly/security/sasl/test/BaseTestCase.java
Labels: +1 DAL, +1 FJ

#1175 [ELY-1636] Update AcmeChallenge.Type to be able to handle unknown challenge types
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeChallenge.java
Labels: +1 DAL, +1 HK

#1179 [ELY-1647] Add TRACE messages to allow debugging of the loading of the client side configuration.
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
Labels: +1 FJ, +1 HK

#1178 [ELY-1639] algorithm, provider into key-store-ssl-certificate in Elytron XML for FIPS PKCS11
  pom.xml
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/auth/client/ConfigurationKeyManager.java
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  src/main/resources/schema/elytron-client-1_2.xsd
  src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
  src/test/resources/org/wildfly/security/auth/client/test-wildfly-config-v1_2.xml
  src/test/resources/schema/wrapped-elytron-client-1_2.xsd
Labels: +1 DAL, +1 FJ

#1180 [ELY-1510] Bearer authentication sends 401 to unportected resources when no auth in progress
  src/main/java/org/wildfly/security/http/impl/BearerTokenAuthenticationMechanism.java
Labels: +1 DAL, +1 PI, 1.1.x, INSUFFICIENT ACKS
