Repository wildfly-security/wildfly-elytron, pull requests merged in 2018-05, with the labels that each got.

#1108 [ELY-1532] Deprecate AuthenticationConfiguration properties: useHost, useProtocol, usePort
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
  src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  src/main/resources/schema/elytron-1_0.xsd
  src/main/resources/schema/elytron-1_0_1.xsd
  src/main/resources/schema/elytron-client-1_1.xsd
Labels: +1 FJ, +1 HK, 1.3.x

#1127 [ELY-1480] Coverity, Explicit null dereferenced in FileSystemSecurityRealm
  src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
Labels: +1 DAL, +1 HK, 1.3.x

#1128 [ELY-1564] In PasswordKeyMapper an exception is logged with a wrong algorithm name.
  src/main/java/org/wildfly/security/auth/realm/jdbc/mapper/PasswordKeyMapper.java
Labels: +1 DAL, +1 HK, 1.3.x

#1131 [ELY-1540] added japicmp dependencies for JDK 9
  pom.xml
Labels: +1 DAL, +1 DML, 1.4.x

#1123 [ELY-1398] Verify public API signatures during build.
  pom.xml
Labels: 1.1.x

#1136 [ELY-1460] External CS, PKCS11 can't be configured with externalPath
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
Labels: 1.1.x

#1130 [ELY-1529] one MockWebServer init per OAuth test for less often binding fails
  src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientV10Test.java
  src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientV11Test.java
Labels: +1 DAL, +1 FJ, 1.4.x

#1143 [ELY-657] Updated OAuth2Client error message for unsupported callbacks
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2Client.java
Labels: +1 FJ, +1 HK

#1142 [ELY-1589][ELY-1568] fixed CRL from resource/uri, XSD fix of provider
  pom.xml
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  src/main/resources/schema/elytron-1_0.xsd
  src/main/resources/schema/elytron-1_0_1.xsd
  src/main/resources/schema/elytron-client-1_1.xsd
  src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
  src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
  src/test/resources/org/wildfly/security/auth/client/test-wildfly-config-v1_1.xml
  src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_1.xml
  src/test/resources/schema/wrapped-elytron-1_0.xsd
  src/test/resources/schema/wrapped-elytron-client-1_1.xsd
Labels: +1 DAL, +1 FJ, 1.3.x, Critical

#1144 [ELY-1592] Ensure the context ClassLoader is set of all calls to initSecContext.
  src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClient.java
  src/main/java/org/wildfly/security/sasl/gssapi/GssapiClient.java
Labels: +1 DML, +1 HK, 1.3.x, Critical

#1138 [ELY-1582] hex/base64 encoding of password in JDBC
  src/main/java/org/wildfly/security/auth/realm/jdbc/mapper/PasswordKeyMapper.java
  src/test/java/org/wildfly/security/auth/realm/jdbc/PasswordSupportTest.java
Labels: +1 DAL, +1 DML

#1145 [ELY-1587] ASN.1 decoding extended - UTF8String, BMPString...
  pom.xml
  src/main/java/org/wildfly/security/asn1/ASN1Decoder.java
  src/main/java/org/wildfly/security/asn1/DERDecoder.java
  src/main/java/org/wildfly/security/asn1/util/ASN1.java
  src/main/java/org/wildfly/security/x500/util/X500PrincipalUtil.java
  src/test/java/org/wildfly/security/x500/util/X500PrincipalUtilTest.java
Labels: +1 DML, +1 FJ

#1139 [ELY-1583] adding more TRACEs into keystore and properties realms
  src/main/java/org/wildfly/security/auth/realm/KeyStoreBackedSecurityRealm.java
  src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
Labels: +1 DAL, +1 FJ

#1140 [ELY-1588] credential-store-reference: handled missing alias, xsd doc
  src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  src/main/resources/schema/elytron-client-1_1.xsd
Labels: +1 DAL, +1 FJ
