Repository wildfly-security/wildfly-elytron, pull requests merged in 2019-12, with the labels that each got.

#1351 [ELY-1908] Typo in SimpleSecurityEventFormatter
  audit/src/main/java/org/wildfly/security/audit/SimpleSecurityEventFormatter.java
Labels: +1 FJ, 1.x

#1352 [ELY-1903] Emit SecurityEvent when RealmUnavailableException is thrown
  audit/src/main/java/org/wildfly/security/audit/JsonSecurityEventFormatter.java
  audit/src/main/java/org/wildfly/security/audit/SimpleSecurityEventFormatter.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SecurityEventVisitor.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SecurityRealmUnavailableEvent.java
Labels: +1 DAL, +1 FJ, 1.x

#1309 [ELY-1853] WS integration with WildFly Elytron - AuthenticationClient…
  auth/client/pom.xml
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/client/src/main/java/org/wildfly/security/auth/client/spi/WebServicesClientConfigProviderImpl.java
  auth/client/src/main/resources/schema/elytron-client-1_5.xsd
  auth/client/src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
  auth/client/src/test/resources/org/wildfly/security/auth/client/test-wildfly-config-v1_5.xml
  pom.xml
  tests/base/pom.xml
  tests/base/src/test/resources/schema/wrapped-elytron-client-1_5.xsd
Labels: +1 DAL, +1 FJ, 1.x, Feature Request

#1356 [ELY-1913] Upgrade nimbus-jose-jwt to 8.2.1.
  pom.xml
Labels: +1 FJ, 1.x

#1357 [ELY-1914] Upgrade org.jboss.logging tools to 2.2.1.Final
  pom.xml
Labels: +1 FJ, 1.x
