Repository wildfly-security/wildfly-elytron, pull requests merged in 2019-07, with the labels that each got.

#1299 [ELY-1839] Move the schemas to the wildfly-elytron-client module and update the test files accordingly
  auth/client/src/main/resources/schema/elytron-1_0.xsd
  auth/client/src/main/resources/schema/elytron-1_0_1.xsd
  auth/client/src/main/resources/schema/elytron-client-1_1.xsd
  auth/client/src/main/resources/schema/elytron-client-1_2.xsd
  auth/client/src/main/resources/schema/elytron-client-1_3.xsd
  auth/client/src/main/resources/schema/elytron-client-1_4.xsd
  tests/base/pom.xml
  tests/base/src/test/resources/schema/wrapped-elytron-1_0.xsd
  tests/base/src/test/resources/schema/wrapped-elytron-client-1_1.xsd
  tests/base/src/test/resources/schema/wrapped-elytron-client-1_2.xsd
  tests/base/src/test/resources/schema/wrapped-elytron-client-1_3.xsd
  tests/base/src/test/resources/schema/wrapped-elytron-client-1_4.xsd
Labels: +1 DAL, +1 DV, 1.x

#1301 [ELY-1844] Upgrade Apache commons-cli to version 1.4
  pom.xml
Labels: +1 DV, +1 FJ

#1297 [ELY-816] [ELY-867] Support for masked passwords in client XML config
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronMessages.java
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/client/src/main/java/org/wildfly/security/credential/source/OAuth2CredentialSource.java
  auth/client/src/main/resources/schema/elytron-client-1_4.xsd
  auth/client/src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
  auth/client/src/test/resources/org/wildfly/security/auth/client/test-wildfly-config-v1_2.xml
  auth/client/src/test/resources/org/wildfly/security/auth/client/test-wildfly-config-v1_4.xml
  base/src/main/java/org/wildfly/security/WildFlyElytronProvider.java
  credential/base/src/main/java/org/wildfly/security/password/interfaces/MaskedPassword.java
  credential/base/src/main/java/org/wildfly/security/password/interfaces/RawMaskedPassword.java
  credential/base/src/main/java/org/wildfly/security/password/spec/MaskedPasswordAlgorithmSpec.java
  credential/base/src/main/java/org/wildfly/security/password/spec/MaskedPasswordSpec.java
  credential/base/src/main/java/org/wildfly/security/password/util/ModularCrypt.java
  password/impl/src/main/java/org/wildfly/security/password/impl/ElytronMessages.java
  password/impl/src/main/java/org/wildfly/security/password/impl/MaskedPasswordAlgorithmParametersSpiImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/MaskedPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java
  password/impl/src/test/java/org/wildfly/security/password/impl/MaskedPasswordPicketBoxCompatibilityTest.java
  password/impl/src/test/java/org/wildfly/security/password/impl/MaskedPasswordTest.java
  tests/base/src/test/java/org/wildfly/security/auth/client/MaskedPasswordSSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/auth/client/MaskedPasswordSaslAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/util/AbstractAlgorithmParametersSpiImplTest.java
  tests/base/src/test/resources/org/wildfly/security/auth/client/wildfly-masked-password-sasl-config-v1_4.xml
  tests/base/src/test/resources/org/wildfly/security/auth/client/wildfly-masked-password-ssl-config-v1_4.xml
Labels: +1 DAL, +1 FJ, 1.x, Feature Request

#1303 [ELY-1847] Use correct class name for 'BearerMechanismFactory'.
  base/src/main/java/org/wildfly/security/WildFlyElytronProvider.java
Labels: +1 FJ, 1.x, Critical

#1306 [ELY-1849] Ensure all the 'digest' password types are available from the provider.
  sasl/digest/src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
  sasl/digest/src/main/java/org/wildfly/security/sasl/digest/WildFlyElytronSaslDigestProvider.java
Labels: +1 FJ, 1.x

#1308 [ELY-1852] Identify and restrict current message ID ranges.
  ELY_Messages.txt
  asn1/src/main/java/org/wildfly/security/asn1/ElytronMessages.java
  audit/src/main/java/org/wildfly/security/audit/ElytronMessages.java
  auth/client/src/main/java/org/wildfly/security/credential/source/ElytronMessages2.java
  auth/jaspi/src/main/java/org/wildfly/security/auth/jaspi/_private/ElytronMessages.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/ElytronMessages.java
  auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/_private/ElytronMessages.java
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/ElytronMessages.java
  auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/_private/ElytronMessages.java
  auth/util/src/main/java/org/wildfly/security/auth/util/ElytronMessages.java
  base/src/main/java/org/wildfly/security/ElytronMessages.java
  credential/base/src/main/java/org/wildfly/security/credential/_private/ElytronMessages.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/ElytronMessages.java
  credential/source/impl/src/main/java/org/wildfly/security/credential/source/impl/ElytronMessages.java
  credential/store/src/main/java/org/wildfly/security/credential/store/_private/ElytronMessages.java
  http/base/src/main/java/org/wildfly/security/http/ElytronMessages.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/ElytronMessages.java
  http/util/src/main/java/org/wildfly/security/http/util/ElytronMessages.java
  jacc/src/main/java/org/wildfly/security/authz/jacc/ElytronMessages.java
  keystore/src/main/java/org/wildfly/security/keystore/ElytronMessages.java
  mechanism/base/src/main/java/org/wildfly/security/mechanism/_private/ElytronMessages.java
  mechanism/gssapi/src/main/java/org/wildfly/security/mechanism/gssapi/ElytronMessages.java
  password/impl/src/main/java/org/wildfly/security/password/impl/ElytronMessages.java
  permission/src/main/java/org/wildfly/security/permission/ElytronMessages.java
  sasl/base/src/main/java/org/wildfly/security/sasl/_private/ElytronMessages.java
  ssl/src/main/java/org/wildfly/security/ssl/ElytronMessages.java
  util/src/main/java/org/wildfly/security/util/ElytronMessages.java
  wildfly-elytron/pom.xml
  x500/base/src/main/java/org/wildfly/security/x500/_private/ElytronMessages.java
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/ElytronMessages.java
  x500/cert/base/src/main/java/org/wildfly/security/pem/ElytronMessages.java
  x500/cert/base/src/main/java/org/wildfly/security/pem/Pem.java
  x500/cert/base/src/main/java/org/wildfly/security/x500/cert/CertUtil.java
  x500/cert/base/src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java
  x500/cert/base/src/main/java/org/wildfly/security/x500/cert/SelfSignedX509CertificateAndSigningKey.java
  x500/cert/base/src/main/java/org/wildfly/security/x500/cert/X509CertificateBuilder.java
  x500/cert/base/src/main/java/org/wildfly/security/x500/cert/_private/ElytronMessages.java
  x500/cert/util/src/main/java/org/wildfly/security/x500/cert/util/ElytronMessages.java
Labels: +1 DV, +1 FJ, 1.x

#1304 [ELY-1843] - Adding ability to specify custom ScheduledExecutorService and to shut down ScheduledExecutorService in NonceManager
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/HttpAuthenticationFactory.java
  auth/server/http/src/main/java/org/wildfly/security/auth/server/http/HttpAuthenticationFactory.java
  http/base/src/main/java/org/wildfly/security/http/HttpServerAuthenticationMechanismFactory.java
  http/digest/src/main/java/org/wildfly/security/http/digest/DigestMechanismFactory.java
  http/digest/src/main/java/org/wildfly/security/http/digest/NonceManager.java
Labels: +1 DAL, +1 FJ, 1.x

#1302 [ELY-1841] Update prerecorded messages in AcmeClientSpiTest using lat…
  x500/cert/acme/src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
  x500/cert/acme/src/test/resources/org/wildfly/security/x500/cert/acme/account.keystore
  x500/cert/acme/src/test/resources/org/wildfly/security/x500/cert/acme/readme.txt
Labels: +1 DAL, +1 FJ
