Repository wildfly-security/wildfly-elytron, pull requests merged in 2019-09, with the labels that each got.

#1322 [ELY-1867] and [ELY-1868] Update syslog audit endpoint to use current reconnect attempts in infinite case and Fix syslog audit endpoint udp infinite test case
  audit/src/main/java/org/wildfly/security/audit/SyslogAuditEndpoint.java
  tests/base/src/test/java/org/wildfly/security/audit/SyslogAuditEndpointTest.java
Labels: +1 DAL, +1 FJ, Critical

#1325 [ELY-1873] Allow for modifications to the permissions in the returned PermissionCollection.
  jacc/src/main/java/org/wildfly/security/authz/jacc/JaccDelegatingPolicy.java
Labels: +1 DV, +1 FJ, Critical

#1324 [ELY-1845] Elytron wildfly-elytron-realm module contains wrong name i…
  auth/realm/base/pom.xml
Labels: +1 FJ
