Repository wildfly-security/wildfly-elytron, pull requests merged in 2019-02, with the labels that each got.

#1230 ELY-1748, add support for mapping from the token claims to principal name.
  auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/TokenSecurityRealm.java
  tests/base/src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
Labels: +1 DAL, +1 DML

#1231 [ELY-1753] Ensure the sources jar is produced for org.wildfly.security.wildfly-elytron
  wildfly-elytron/pom.xml
Labels: +1 DAL, 1.9.x

#1219 [ELY-1693] Update AcmeClientSpi to make use of POST-as-GET requests instead of GET requests and update tests accordingly
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
  src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
Labels: 1.6.x

#1220 [ELY-1678] Avoid NPE in AcmeClientSpi#checkContentType() and [ELY-1699] Intermittently failing AcmeClientSpiTest
  src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
  src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
Labels: 1.6.x

#1221 [ELY-1702] Update mockserver-netty to 5.4.1
  pom.xml
  src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
Labels: 1.6.x

#1224 [ELY-1747] If programmatic authentication is successful associate the credential with the identity.
  src/main/java/org/wildfly/security/http/HttpAuthenticator.java
Labels: 1.6.x

#1233 [ELY-1464] Programatic authentication should be caching the SecurityIdentity not the name of the identity
  src/main/java/org/wildfly/security/cache/CachedIdentity.java
  src/main/java/org/wildfly/security/http/HttpAuthenticator.java
Labels: +1 FJ, 1.6.x

#1235 [ELY-1691] Add test if Mechansim Database cover cipher suites from JDK
  src/test/java/org/wildfly/security/ssl/MechanismDatabaseTest.java
Labels: +1 FJ, 1.8.x

#1244 [ELY-1677] Elytron Bearer Token Authentication - Return a 401 on Invalid Token
  src/main/java/org/wildfly/security/http/impl/BearerTokenAuthenticationMechanism.java
Labels: +1 DAL, +1 FJ

#1245 [ELY-1703] Intermittent failure of PrincipalMappingSuiteChild#testDnToDnVerify
  src/test/java/org/wildfly/security/ldap/PrincipalMappingSuiteChild.java
Labels: +1 FJ

#1246 [ELY-1756] [ELY-1757] Fix Elytron-Tool Test Failures on Windows
  tool/src/main/java/org/wildfly/security/tool/FileSystemRealmCommand.java
  tool/src/test/java/org/wildfly/security/tool/FileSystemRealmCommandTest.java
  tool/src/test/java/org/wildfly/security/tool/MaskCommandTest.java
Labels: +1 FJ
