Repository wildfly-security/wildfly-elytron, pull requests merged in 2019-10, with the labels that each got.

#1337 [ELY-1872] elytron-tool.sh usage with symbolic links
  ELY_Messages.txt
  credential/store/src/main/java/org/wildfly/security/credential/store/_private/ElytronMessages.java
  credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
  credential/store/src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
Labels: +1 DAL, +1 FJ, 1.x

#1330 [ELY-1872] elytron-tool.sh usage with symbolic links
  src/main/java/org/wildfly/security/_private/ElytronMessages.java
  src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
  src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
Labels: 1.6.x

#1338 [ELY-1885] Component Upgrades
  pom.xml
Labels: +1 FJ

#1339 [ELY-1886][ELY-1887] Switch to the JBoss / Jakarta Fork for JACC and JASPI
  pom.xml
Labels: +1 DAL, 1.x

#1329 [ELY-1876] Log messages are not logged when KeyStoreCredentialStore is initialized with Provider[] in getKeyStoreInstance.
  credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
Labels: +1 DV, +1 FJ, 1.x
