Repository wildfly-security/wildfly-elytron, pull requests merged in 2019-03, with the labels that each got.

#1247 [ELY-1760] Make ModularCrypt alphabets package private
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/ElytronMessages.java
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordPasswordUtil.java
  credential/base/src/main/java/org/wildfly/security/credential/_private/ElytronMessages.java
  credential/base/src/main/java/org/wildfly/security/password/util/ModularCrypt.java
  credential/base/src/test/java/org/wildfly/security/password/util/PasswordBasedEncryptionUtilTest.java
  tests/base/src/test/java/org/wildfly/security/apacheds/CryptCompatibilityTest.java
  tests/base/src/test/java/org/wildfly/security/util/PasswordBasedEncryptionUtilTest.java
Labels: +1 DAL, 1.x

#1250 [ELY-1711] Include JAPICMP Plug-In but Switched Off
  pom.xml
  wildfly-elytron/pom.xml
Labels: 1.x

#1229 [ELY-1711] Restore JAPICMP Comparison
  pom.xml
  wildfly-elytron/pom.xml
Labels: 1.x

#1254 [ELY-1767] Upgrade org.apache.commons.commons-lang3 to 3.8
  pom.xml
Labels: +1 DAL, 1.x

#1251 [ELY-1711] Add new modules to japicmp config
  pom.xml
Labels: 1.x

#1257 [ELY-1763] Return deprecated Public API 'org.wildfly.security.mechanism.MechanismUtil' class
  mechanism/base/src/main/java/org/wildfly/security/mechanism/MechanismUtil.java
Labels: +1 DAL

#1258 [ELY-1769] Add missing SCRAM password algorithms for translation.
  password/impl/src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java
Labels: +1 FJ, 1.x

#1259 [ELY-1770] Ignore methods failing JAPICMP comparison where they take private API as parameters.
  pom.xml
  wildfly-elytron/pom.xml
Labels: +1 FJ, 1.x

#1261 [ELY-1774] Reference the factory instead of the mechanism directly.
  base/src/main/java/org/wildfly/security/WildFlyElytronHttpBearerProvider.java
Labels: +1 FJ, 1.x

#1260 [ELY-1773] Upgrade WildFly Common to 1.5.0.Final
  pom.xml
Labels: 1.x
