Repository wildfly-security/wildfly-elytron, pull requests merged in 2019-08, with the labels that each got.

#1319 [ELY-1854] Add the ability to specify whether or not the AccessContro…
  src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
  src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java
Labels: +1 DAL, +1 FJ, 1.6.x

#1311 [ELY-1855] Add AuthenticationConfiguration#captureAuthorizationIdentity method to avoid needing an extra call to AuthenticationConfiguration#useForwardedAuthorizationIdentity
  src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
  src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java
Labels: +1 DAL, +1 DV, 1.6.x

#1292 [ELY-1804] Add support for aggregating attributes from multiple security realms.
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateAttributes.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateAttributesTest.java
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateRealmTest.java
  auth/server/base/src/main/java/org/wildfly/security/authz/AuthorizationIdentity.java
Labels: +1 DV, +1 FJ, 1.x, Feature Request

#1312 [ELY-1856] Update a message ID for wildly-elytron-mechanism-gssapi in ELY_Messages.txt
  ELY_Messages.txt
Labels: +1 DAL, +1 DV, 1.x

#1300 [ELY-1712] Enhanced Audit Logging - RFC Support and Configuring Reconnects
  ELY_Messages.txt
  audit/pom.xml
  audit/src/main/java/org/wildfly/security/audit/ElytronMessages.java
  audit/src/main/java/org/wildfly/security/audit/JsonSecurityEventFormatter.java
  audit/src/main/java/org/wildfly/security/audit/SimpleSecurityEventFormatter.java
  audit/src/main/java/org/wildfly/security/audit/SyslogAuditEndpoint.java
  auth/server/base/pom.xml
  auth/server/base/src/main/java/org/wildfly/security/auth/server/event/Rfc3164SyslogEvent.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/event/Rfc5424SyslogEvent.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SecurityEventVisitor.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SyslogAuditEvent.java
  pom.xml
  tests/base/pom.xml
  tests/base/src/test/java/org/wildfly/security/audit/JsonSecurityEventFormatterTest.java
  tests/base/src/test/java/org/wildfly/security/audit/SimpleSyslogServer.java
  tests/base/src/test/java/org/wildfly/security/audit/SyslogAuditEndpointTest.java
Labels: +1 DAL, +1 FJ, 1.x, Feature Request

#1320 [ELY-1862] Fix infinite loop in SecurityEventVisitor#handleSyslogAudi…
  auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SecurityEventVisitor.java
Labels: +1 DAL, +1 FJ, 1.x, Critical

#1321 [ELY-1864] Do not attempt to reconnect in an endless loop when a UDP …
  audit/src/main/java/org/wildfly/security/audit/ElytronMessages.java
  audit/src/main/java/org/wildfly/security/audit/SyslogAuditEndpoint.java
  tests/base/src/test/java/org/wildfly/security/audit/SyslogAuditEndpointTest.java
Labels: +1 DAL, +1 FJ
