Repository wildfly-security/wildfly-elytron, pull requests merged in 2019-06, with the labels that each got.

#1286 [ELY-613] Changed some inner classes to be static nested classes
  asn1/src/main/java/org/wildfly/security/asn1/DERDecoder.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/JaasSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
  keystore/src/main/java/org/wildfly/security/keystore/AtomicLoadKeyStore.java
Labels: +1 DAL, +1 FJ, 1.x

#1288 [ELY-1784] Allowing custom executor services in SaslAuthenticationFac…
  auth/server/base/pom.xml
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
  auth/server/sasl/src/main/java/org/wildfly/security/auth/server/sasl/SaslAuthenticationFactory.java
  sasl/base/src/main/java/org/wildfly/security/sasl/util/AuthenticationTimeoutSaslServerFactory.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslAuthenticationTimeoutTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
Labels: +1 DAL, +1 FJ, 1.x

#1279 [ELY-1634] LDAPS referrals broken
  src/main/java/org/wildfly/security/auth/realm/ldap/DelegatingLdapContext.java
Labels: 1.6.x

#1284 [ELY-1810] Only check the permission against the current SecurityIdentity if it is a JACC permission.
  src/main/java/org/wildfly/security/authz/jacc/JaccDelegatingPolicy.java
Labels: 1.6.x

#1293 [ELY-1826] Cannot connect to management interface with Java Security Manager enabled
  src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
Labels: 1.6.x

#1290 [ELY-1792] Fixed errors for VaultCommandTest on IBM java
  tool/src/test/java/org/wildfly/security/tool/VaultCommandTest.java
  tool/src/test/resources/bulk-vault-conversion-desc-ibm
  tool/src/test/resources/vault-v1-more/readme.txt
  tool/src/test/resources/vault-v1-more/vault-jceks-ibm.keystore
  tool/src/test/resources/vault-v1-more/vault_data_ibm/VAULT.dat
  tool/src/test/resources/vault-v1/readme.txt
  tool/src/test/resources/vault-v1/vault-jceks-ibm.keystore
  tool/src/test/resources/vault-v1/vault_data_ibm/VAULT.dat
Labels: +1 DAL, +1 FJ, 1.x

#1280 [ELY-1797] Make the certificate authority used by a certificate-autho…
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/AcmeAccount.java
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/CertificateAuthority.java
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/ElytronMessages.java
Labels: +1 DAL, +1 FJ, 1.x, Feature Request

#1291 [ELY-1818] / [ELY-1820] / [ELY-1821] / [ELY-1823] / [ELY-1824] Performance optimisations
  base/src/main/java/org/wildfly/security/WildFlyElytronBaseProvider.java
  base/src/main/java/org/wildfly/security/WildFlyElytronHttpBasicProvider.java
  base/src/main/java/org/wildfly/security/WildFlyElytronHttpBearerProvider.java
  base/src/main/java/org/wildfly/security/WildFlyElytronHttpClientCertProvider.java
  base/src/main/java/org/wildfly/security/WildFlyElytronHttpDigestProvider.java
  base/src/main/java/org/wildfly/security/WildFlyElytronHttpFormProvider.java
  base/src/main/java/org/wildfly/security/WildFlyElytronHttpSpnegoProvider.java
  base/src/main/java/org/wildfly/security/WildFlyElytronProvider.java
  http/base/src/main/java/org/wildfly/security/http/HttpAuthenticator.java
  http/basic/src/main/java/org/wildfly/security/http/basic/WildFlyElytronHttpBasicProvider.java
  http/bearer/src/main/java/org/wildfly/security/http/bearer/WildFlyElytronHttpBearerProvider.java
  http/cert/src/main/java/org/wildfly/security/http/cert/WildFlyElytronHttpClientCertProvider.java
  http/digest/src/main/java/org/wildfly/security/http/digest/WildFlyElytronHttpDigestProvider.java
  http/form/src/main/java/org/wildfly/security/http/form/WildFlyElytronHttpFormProvider.java
  http/spnego/src/main/java/org/wildfly/security/http/spnego/WildFlyElytronHttpSpnegoProvider.java
  http/util/src/main/java/org/wildfly/security/http/util/SecurityProviderServerMechanismFactory.java
  provider/util/src/main/java/org/wildfly/security/provider/util/ProviderUtil.java
  sasl/anonymous/src/main/java/org/wildfly/security/sasl/anonymous/WildFlyElytronSaslAnonymousProvider.java
  sasl/digest/src/main/java/org/wildfly/security/sasl/digest/WildFlyElytronSaslDigestProvider.java
  sasl/entity/src/main/java/org/wildfly/security/sasl/entity/WildFlyElytronSaslEntityProvider.java
  sasl/external/src/main/java/org/wildfly/security/sasl/external/WildFlyElytronSaslExternalProvider.java
  sasl/gs2/src/main/java/org/wildfly/security/sasl/gs2/WildFlyElytronSaslGs2Provider.java
  sasl/gssapi/src/main/java/org/wildfly/security/sasl/gssapi/WildFlyElytronSaslGssapiProvider.java
  sasl/oauth2/src/main/java/org/wildfly/security/sasl/oauth2/WildFlyElytronSaslOAuth2Provider.java
  sasl/otp/src/main/java/org/wildfly/security/sasl/otp/WildFlyElytronSaslOTPProvider.java
  sasl/plain/src/main/java/org/wildfly/security/sasl/plain/WildFlyElytronSaslPlainProvider.java
  sasl/scram/src/main/java/org/wildfly/security/sasl/scram/WildFlyElytronSaslScramProvider.java
Labels: +1 FJ, 1.x

#1269 [ELY-1617] Support SSL Certificate revocation using OCSP
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  pom.xml
  ssl/src/main/java/org/wildfly/security/ssl/ElytronMessages.java
  ssl/src/main/java/org/wildfly/security/ssl/X509CRLExtendedTrustManager.java
  ssl/src/main/java/org/wildfly/security/ssl/X509RevocationTrustManager.java
  tests/base/pom.xml
  tests/base/src/main/resources/schema/elytron-client-1_4.xsd
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/ssl/TestingOcspServer.java
  tests/base/src/test/resources/org/wildfly/security/ssl/ocsp-db.properties
  tests/base/src/test/resources/org/wildfly/security/ssl/ocsp-responder.xml
  tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_1.xml
  tests/base/src/test/resources/schema/wrapped-elytron-client-1_4.xsd
Labels: +1 DAL, +1 FJ, 1.x, Feature Request

#1294 [ELY-1800] Add the ability to decode the Principal from Evidence
  auth/server/base/src/main/java/org/wildfly/security/auth/callback/EvidenceDecodePrincipalCallback.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/EvidenceDecoder.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ModifiableSecurityRealm.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityRealm.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
  credential/base/src/main/java/org/wildfly/security/evidence/Evidence.java
  credential/base/src/main/java/org/wildfly/security/evidence/X509PeerCertificateChainEvidence.java
  http/cert/src/main/java/org/wildfly/security/http/cert/ClientCertAuthenticationMechanism.java
  sasl/base/src/main/java/org/wildfly/security/sasl/util/TrustManagerSaslServerFactory.java
  sasl/entity/src/main/java/org/wildfly/security/sasl/entity/EntitySaslServer.java
  tests/base/src/test/java/org/wildfly/security/x500/X509PeerCertificateChainEvidenceDecoderTest.java
  x500/principal/src/main/java/org/wildfly/security/x500/principal/X500SubjectEvidenceDecoder.java
  x500/principal/src/main/java/org/wildfly/security/x500/principal/X509SubjectAltNameEvidenceDecoder.java
Labels: +1 DAL, 1.x, Feature Request
