Repository wildfly-security/wildfly-elytron, pull requests merged in 2019-11, with the labels that each got.

#1346 [ELY-1898] Update usages of SecurityFactory<Credential> to SecurityFactory<? extends Credential>
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/MechanismConfiguration.java
  auth/server/base/src/main/java/org/wildfly/security/credential/source/CredentialSource.java
Labels: +1 DAL, 1.x, Critical

#1343 [ELY-1895] Ignore failure scenario testing as bad UDP host does not trigger the failure in all environments.
  tests/base/src/test/java/org/wildfly/security/audit/SyslogAuditEndpointTest.java
Labels: +1 FJ, 1.x

#1342 [ELY-1895] Ignore failure scenario testing as bad UDP host does not trigger the failure in all environments.
  tests/base/src/test/java/org/wildfly/security/audit/SyslogAuditEndpointTest.java
Labels: 1.10.x, Maintenance

#1323 [ELY-1866] Fixed broken symbolic link to LICENSE.txt
  LICENSE.txt
Labels: +1 DAL, +1 DV, 1.x

#1326 [ELY-1874] Fix for checking maxCertPath specified in X509RevocationTr…
  ssl/src/main/java/org/wildfly/security/ssl/X509RevocationTrustManager.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Labels: +1 DAL, +1 DV, 1.x

#1313 [ELY-1715] Remove 'wildfly-elytron-auth-server-deprecated'
  auth/server/deprecated/pom.xml
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/ElytronMessages.java
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/HttpAuthenticationFactory.java
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/SaslAuthenticationFactory.java
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/SecurityIdentityServerMechanismFactory.java
  pom.xml
  wildfly-elytron/pom.xml
Labels: +1 DV, +1 FJ, master

#1348 [ELY-1901] Upgrade JBoss Modules to 1.9.2.Final
  pom.xml
Labels: +1 FJ, 1.x

#1314 [ELY-1717] Remove 'wildfly-elytron-credential-source-deprecated'
  credential/source/deprecated/pom.xml
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/CallbackHandlerCredentialSource.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/CommandCredentialSource.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/CredentialStoreCredentialSource.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/ElytronMessages.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/FactoryCredentialSource.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/KeyStoreCredentialSource.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/LocalKerberosCredentialSource.java
  pom.xml
  wildfly-elytron/pom.xml
Labels: +1 DV, +1 FJ, master

#1315 [ELY-1720] Remove 'wildfly-elytron-sasl-deprecated'
  pom.xml
  sasl/deprecated/pom.xml
  sasl/deprecated/src/main/java/org/wildfly/security/sasl/util/AuthenticationContextSaslClient.java
  sasl/deprecated/src/main/java/org/wildfly/security/sasl/util/AuthenticationContextSaslClientFactory.java
  sasl/deprecated/src/main/java/org/wildfly/security/sasl/util/AuthenticationContextSaslServer.java
  sasl/deprecated/src/main/java/org/wildfly/security/sasl/util/AuthenticationContextSaslServerFactory.java
  wildfly-elytron/pom.xml
Labels: +1 DV, +1 FJ, master

#1350 [ELY-1905] Refactor SSL Session validation in SSLAuthenticationTest
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Labels: +1 DAL, +1 FJ, 1.x

#1316 [ELY-1718] Remove 'wildfly-elytron-http-deprecated'
  http/deprecated/pom.xml
  http/deprecated/src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java
  pom.xml
  wildfly-elytron/pom.xml
Labels: +1 DV, +1 FJ, master

#1317 [ELY-1722] Remove 'wildfly-elytron-x500-deprecated'
  pom.xml
  wildfly-elytron/pom.xml
  x500/deprecated/pom.xml
  x500/deprecated/src/main/java/org/wildfly/security/x500/ElytronMessages.java
  x500/deprecated/src/main/java/org/wildfly/security/x500/X500AttributePrincipalDecoder.java
Labels: +1 DV, +1 FJ, master

#1318 [ELY-1728] Remove 'org.wildfly.security.auth.util.GSSCredentialSecuri…
  auth/util/pom.xml
  auth/util/src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
  wildfly-elytron/pom.xml
Labels: +1 DV, +1 FJ, master
