Repository wildfly-security/wildfly-elytron, pull requests merged in 2019-04, with the labels that each got.

#1253 [ELY-1761] Add property to skip normalization
  sasl/base/src/main/java/org/wildfly/security/sasl/WildFlySasl.java
  sasl/base/src/main/java/org/wildfly/security/sasl/util/StringPrep.java
  sasl/plain/src/main/java/org/wildfly/security/sasl/plain/PlainSaslClient.java
  sasl/plain/src/main/java/org/wildfly/security/sasl/plain/PlainSaslClientFactory.java
  tests/base/src/test/java/org/wildfly/security/sasl/plain/PlainTest.java
Labels: +1 FJ, 1.x

#1263 [ELY-1779] Make the package 'org.wildfly.security.password.util' public API.
  pom.xml
  wildfly-elytron/pom.xml
Labels: +1 FJ, 1.x

#1266 [ELY-1782] Update the branch referenced in the Contributions section …
  README.md
Labels: +1 FJ, 1.x

#1270 [ELY-1786] / [ELY-1787] Logging and WildFly Common Component Upgrades
  pom.xml
Labels: +1 FJ

#1271 [ELY-1789] Add a global property for the Maven XML plugin in the tests module
  tests/base/pom.xml
Labels: +1 FJ

#1272 [ELY-1788] Update minimum JDK build version to 11
  .travis.yml
  pom.xml
Labels: +1 FJ

#1273 [ELY-1793] Cache JsonProvider
  audit/src/main/java/org/wildfly/security/audit/JsonSecurityEventFormatter.java
Labels: +1 DAL

#1274 [ELY-1794] Check if we have a FORM submission before attempting to restore an identity.
  http/form/src/main/java/org/wildfly/security/http/form/FormAuthenticationMechanism.java
Labels: +1 FJ

#1275 [ELY-1790] Include 'wildfly-elytron-password-impl' in the Tool distribution.
  tool/pom.xml
Labels: +1 FJ, Critical
