Repository wildfly-security/wildfly-elytron, pull requests merged in 2020-08, with the labels that each got.

#1354 [ELY-1902] Support for multiple security realms - Failover
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/ElytronMessages.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FailoverSecurityRealm.java
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/FailoverRealmTest.java
  auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/JdbcSecurityRealm.java
  auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/_private/ElytronMessages.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/_private/ElytronMessages.java
  permission/src/main/java/org/wildfly/security/permission/ElytronPermission.java
Labels: +1 DAL, +1 FJ, 1.x, Feature Request

#1427 [ELY-1964] Some SecurityRealm implementations use wrong exception types when unavailable
  auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/JdbcSecurityRealm.java
  auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/_private/ElytronMessages.java
Labels: +1 FJ, 1.x

#1432 [JBEAP-19613]/[JBEAP-19615] Update AcmeClientSpi#obtainCertificate so that it obtains the order URL from the response to newOrder
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/Acme.java
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/ElytronMessages.java
  x500/cert/acme/src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
Labels: Maintenance

#1414 [ELY-1995] Ensure that the authorization identity can be found when using an AggregateSecurityRealm where evidence that does not have a principal is being verified
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java
  tests/base/src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslTest.java
Labels: +1 DAL, +1 MM, Maintenance
