Repository wildfly-security/wildfly-elytron, pull requests merged in 2020-12, with the labels that each got.

#1418 [ELY-1987] Add the ability to adjust the case of a user name using an Elytron principal transformer
  auth/util/src/main/java/org/wildfly/security/auth/util/CaseNameRewriter.java
  tests/base/src/test/java/org/wildfly/security/auth/server/CaseNameRewriterTest.java
Labels: +1 DV, +1 FJ, 1.x, Feature Request

#1468 [ELY-2042] ElytronXMLParser is not configuring maximum-cert-path in X509RevocationTrustManager
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
  tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_1.xml
Labels: +1 DAL, +1 FJ

#1466 ELY-2049 Add WildFly SecurityManager findAccessDenial trace capability
  manager/base/src/main/java/org/wildfly/security/manager/WildFlySecurityManager.java
  manager/base/src/main/java/org/wildfly/security/manager/_private/SecurityMessages.java
Labels: +1 DAL, +1 FJ

#1473 [ELY-2057] No acceptedIssuers sent when CRLs are configured
  ssl/src/main/java/org/wildfly/security/ssl/X509RevocationTrustManager.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Labels: +1 DAL, +1 FJ, 1.x

#1474 [ELY-2059] Ensure all SSLContext instances exclusively use the installed providers
  tests/base/src/test/resources/org/wildfly/security/auth/client/wildfly-masked-password-ssl-config-v1_4.xml
  tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_1.xml
Labels: +1 FJ

#1475 [ELY-2056] Add a new GitHub workflow to trigger CI for pull requests.
  .github/workflows/pr-ci.yaml
Labels: +1 FJ
