Repository wildfly-security/wildfly-elytron, pull requests merged in 2020-04, with the labels that each got.

#1390 [ELY-1954] If there is no request path and the application has a context root, redirect to ensure a trailing slash is on the URL.
  http/form/src/main/java/org/wildfly/security/http/form/FormAuthenticationMechanism.java
Labels: +1 DV, +1 FJ, 1.x

#1355 [ELY-1894] Add the ability to make use of the IP address of a remote client when making authorization decisions
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateAttributesTest.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
  auth/server/base/src/main/java/org/wildfly/security/authz/AggregateAttributes.java
  auth/server/base/src/main/java/org/wildfly/security/authz/AuthorizationIdentity.java
  auth/server/base/src/main/java/org/wildfly/security/authz/RoleDecoder.java
  auth/server/base/src/main/java/org/wildfly/security/authz/SourceAddressRoleDecoder.java
  auth/server/base/src/test/java/org/wildfly/security/authz/RoleDecoderTest.java
  tests/base/src/test/java/org/wildfly/security/auth/server/SourceAddressRuntimeAttributesTest.java
Labels: +1 DAL, +1 MM, 1.x, Feature Request

#1383 [ELY-1838] Differentiate actions and parameters
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/main/java/org/wildfly/security/tool/FileSystemRealmCommand.java
  tool/src/main/java/org/wildfly/security/tool/MaskCommand.java
  tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
Labels: +1 DAL, +1 FJ, 1.x

#1372 [ELY-1519] Make restore of SecurityIdentity on replicated session configurable
  http/base/src/main/java/org/wildfly/security/http/HttpConstants.java
  http/spnego/src/main/java/org/wildfly/security/http/spnego/SpnegoAuthenticationMechanism.java
Labels: +1 DAL, +1 FJ, 1.x

#1393 [ELY-1958] Remove Travis configuration from project.
  .travis-settings.xml
  .travis.yml
Labels: +1 FJ, 1.x
