Repository wildfly-security/wildfly-elytron, pull requests merged in 2020-01, with the labels that each got.

#1359 [ELY-1831] When manipulating a store the password should only be prom…
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
Labels: +1 DAL, +1 FJ, 1.x

#1358 [ELY-1884] Adding MicroProfile JWT Support
  jwt/pom.xml
  jwt/src/main/java/org/wildfly/security/mp/jwt/JWTCDIExtension.java
  jwt/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  pom.xml
  wildfly-elytron/pom.xml
Labels: +1 FJ, 1.x

#1295 [ELY-1706] Add support for TLS 1.3 cipher suites
  ELY_Messages.txt
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronMessages.java
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/client/src/main/resources/schema/elytron-client-1_5.xsd
  auth/client/src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
  auth/client/src/test/resources/org/wildfly/security/auth/client/test-wildfly-config-v1_5.xml
  ssl/src/main/java/org/wildfly/security/ssl/CipherSuiteSelector.java
  ssl/src/main/java/org/wildfly/security/ssl/ElytronMessages.java
  ssl/src/main/java/org/wildfly/security/ssl/MechanismDatabase.java
  ssl/src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
  ssl/src/main/java/org/wildfly/security/ssl/SSLExplorer.java
  ssl/src/main/java/org/wildfly/security/ssl/TLS13MechanismDatabase.properties
  ssl/src/test/java/org/wildfly/security/ssl/CipherSuiteSelectorTest.java
  ssl/src/test/java/org/wildfly/security/ssl/MechanismDatabaseTest.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/ssl/TLS13AuthenticationTest.java
  tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_5.xml
Labels: +1 DAL, +1 DV, 1.x, Feature Request

#1361 [ELY-1920] Upgrade SmallRye JWT to 2.0.12
  pom.xml
Labels: +1 DV, +1 FJ

#1364 [ELY-1924] Correct CA certificate generation for EntityTest so it is only generated once.
  sasl/base/src/main/java/org/wildfly/security/sasl/util/TrustManagerSaslServerFactory.java
  tests/base/src/test/java/org/wildfly/security/sasl/entity/EntityTest.java
Labels: +1 FJ

#1363 [ELY-1923] Ensure webServicesProperties is not `null` before accessing.
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
Labels: +1 DV, +1 FJ

#1362 [ELY-1922] Upgrade BouncyCastle to 1.64
  pom.xml
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Labels: +1 DV, +1 FJ

#1365 [ELY-1926] Move wildfly-elytron-password-impl dependency in client fr…
  auth/client/pom.xml
Labels: +1 DAL, +1 FJ, 1.x
