Repository wildfly-security/wildfly-elytron, pull requests merged in 2020-03, with the labels that each got.

#1376 [ELY-1940] Elytron LDAP Squashes Authentication Exception
  src/main/java/org/wildfly/security/auth/realm/ldap/DirectEvidenceVerifier.java
Labels: +1 FJ, 1.6.x, Maintenance

#1379 [ELY-1941] Update the Travis configuration to use OpenJDK 8
  .travis.yml
Labels: 1.6.x

#1380 [ELY-1943] Upgrade WildFly Common 1.5.4.Final
  pom.xml
Labels: +1 DAL, +1 FJ, 1.x

#1373 Add an overview blog post for WildFly 19 and a blog post on TLS 1.3
  _data/navigation.yml
  _layouts/community.html
  _posts/2020-03-18-new-security-features-in-wildfly-19.adoc
  _posts/2020-03-18-tls-13-with-wildfly.adoc
  _posts/2020-03-18-ws-elytron-client-integration.adoc
Labels: website

#1381 [ELY-1944] Exclude the JWT module from the `wildfly-elytron` module.
  wildfly-elytron/pom.xml
Labels: +1 DV, +1 FJ, 1.10.x
