Repository wildfly-security/wildfly-elytron, pull requests merged in 2020-05, with the labels that each got.

#1394 [ELY-1960] Correct Javadoc generation warnings and failure.
  audit/src/main/java/org/wildfly/security/audit/SyslogAuditEndpoint.java
  auth/client/src/main/java/org/wildfly/security/auth/client/CredentialStoreFactory.java
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/CredentialLoader.java
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/EvidenceVerifier.java
  auth/server/base/src/main/java/org/wildfly/security/authz/MappedRoleMapper.java
  keystore/src/main/java/org/wildfly/security/keystore/AliasFilter.java
  password/impl/src/main/java/org/wildfly/security/password/impl/BCryptPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/ScramDigestPasswordImpl.java
  pom.xml
  sasl/digest/src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java
  sasl/digest/src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
  sasl/gs2/src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClient.java
  sasl/otp/src/main/java/org/wildfly/security/sasl/otp/OTPSaslClient.java
  x500/cert/base/src/main/java/org/wildfly/security/x500/cert/InhibitAnyPolicyExtension.java
  x500/cert/base/src/main/java/org/wildfly/security/x500/cert/NameConstraintsExtension.java
  x500/cert/base/src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java
  x500/principal/src/main/java/org/wildfly/security/x500/principal/X509SubjectAltNameEvidenceDecoder.java
Labels: +1 DV, +1 FJ, 1.x

#1395 [ELY-1961] Upgrade JBoss LogManager to 2.1.15.Final
  pom.xml
Labels: +1 DV, +1 FJ, 1.x

#1396 [ELY-1962] Upgrade JBoss Threads to 2.3.4.Final
  pom.xml
Labels: +1 DV, +1 FJ, 1.x

#1397 Add a blog post that covers Elytron's ACME client SPI in detail
  _posts/2020-05-07-elytron-acme-client-implementation.adoc
Labels: website

#1384 [ELY-1952] SSLConfigurator ignores some of the SSLParameters passed in
  ssl/src/main/java/org/wildfly/security/ssl/JDKSpecific.java
  ssl/src/main/java/org/wildfly/security/ssl/SSLConfiguratorImpl.java
  ssl/src/main/java9/org/wildfly/security/ssl/JDKSpecific.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLConfiguratorImplTest.java
Labels: +1 DAL, +1 FJ, 1.x

#1385 [ELY-1953] Elytron tool command execution fails with java.nio.file.NoSuchFileException
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
  tool/src/test/java/org/wildfly/security/tool/CustomPropertiesCredentialStore.java
  tool/src/test/java/org/wildfly/security/tool/CustomPropertiesProvider.java
  tool/src/test/resources/META-INF/services/java.security.Provider
Labels: +1 DAL, +1 DV, 1.x

#1353 [ELY-1909] Using regex for role in Elytron
  ELY_Messages.txt
  auth/server/base/src/main/java/org/wildfly/security/auth/server/_private/ElytronMessages.java
  auth/server/base/src/main/java/org/wildfly/security/authz/RegexRoleMapper.java
  auth/server/base/src/main/java/org/wildfly/security/authz/RegexRoles.java
  auth/server/base/src/test/java/org/wildfly/security/authz/RegexRoleMapperTest.java
Labels: +1 FJ, +1 MM, 1.x, Feature Request

#1400 [ELY-1968] Update error message returned by AcmeClientSpi#getLocation
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/Acme.java
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/ElytronMessages.java
  x500/cert/acme/src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
Labels: +1 FJ, 1.x
