Repository wildfly-security/wildfly-elytron, pull requests merged in 2020-02, with the labels that each got.

#1367 Missing commits from 1.x
  ELY_Messages.txt
  asn1/src/main/java/org/wildfly/security/asn1/DERDecoder.java
  auth/realm/base/pom.xml
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/ElytronMessages.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/JaasSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateRealmEvidenceTest.java
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateRealmTest.java
  auth/server/base/pom.xml
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SecurityEventVisitor.java
  auth/server/sasl/src/main/java/org/wildfly/security/auth/server/sasl/SaslAuthenticationFactory.java
  keystore/src/main/java/org/wildfly/security/keystore/AtomicLoadKeyStore.java
  sasl/base/src/main/java/org/wildfly/security/sasl/util/AuthenticationTimeoutSaslServerFactory.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslAuthenticationTimeoutTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
Labels: master

#1366 [ELY-1928] Update WildFly Common to 1.5.3.Final
  pom.xml
Labels: +1 DV, +1 FJ, 1.x

#1368 [ELY-1929] / [ELY-1924] Correct CA certificate generation for EntityTest
  sasl/base/src/main/java/org/wildfly/security/sasl/util/TrustManagerSaslServerFactory.java
  tests/base/src/test/java/org/wildfly/security/sasl/entity/EntityTest.java
Labels: +1 FJ, 1.10.x, INSUFFICIENT ACKS

#1371 [ELY-1890] Keep file permissions when modifying an existing credential store
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
Labels: +1 DAL, +1 FJ, 1.10.x
