Repository wildfly-security/wildfly-elytron, pull requests merged in 2020-06, with the labels that each got.

#1404 [ELY-1979] Additional methods as added for JEPS-244
  pom.xml
  ssl/pom.xml
  ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLEngine.java
  ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLParameters.java
  ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLSocket.java
  ssl/src/main/java/org/wildfly/security/ssl/SelectingServerSSLEngine.java
Labels: +1 DV, +1 FJ, Critical

#1406 [ELY-1979] Convert ALPN Method Access to Java 9 and boyond.
  pom.xml
  ssl/pom.xml
  ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLEngine.java
  ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLParameters.java
  ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLSocket.java
  ssl/src/main/java/org/wildfly/security/ssl/JDKSpecific.java
  ssl/src/main/java/org/wildfly/security/ssl/SelectingServerSSLEngine.java
  ssl/src/main/java9/org/wildfly/security/ssl/JDKSpecific.java
Labels: +1 DV, Critical

#1410 Add blog posts on automatic credential store updates and source address role decoders for WildFly 20
  _data/navigation.yml
  _layouts/community.html
  _posts/2020-06-08-automatic-credential-store-updates.adoc
  _posts/2020-06-08-using-remote-client-ip-for-authorization.adoc
Labels: website

#1399 [JBEAP-19513] ELY-1954 - Submission for "j_security_check" login does not work if URL has no trailing slash
  src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java
Labels: 1.6.x

#1398 [ELY-1953] Elytron tool command execution fails with java.nio.file.No…
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
  tool/src/test/java/org/wildfly/security/tool/CustomPropertiesCredentialStore.java
  tool/src/test/java/org/wildfly/security/tool/CustomPropertiesProvider.java
  tool/src/test/resources/META-INF/services/java.security.Provider
Labels: 1.10.x

#1391 [ELY-1954] If there is no request path and the application has a context root, redirect to ensure a trailing slash is on the URL.
  http/form/src/main/java/org/wildfly/security/http/form/FormAuthenticationMechanism.java
Labels: +1 DV, 1.10.x

#1407 Backport ELY-1979, ELY-1981 and ELY-1952
  ssl/pom.xml
  ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLEngine.java
  ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLParameters.java
  ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLSocket.java
  ssl/src/main/java/org/wildfly/security/ssl/JDKSpecific.java
  ssl/src/main/java/org/wildfly/security/ssl/SSLConfiguratorImpl.java
  ssl/src/main/java/org/wildfly/security/ssl/SelectingServerSSLEngine.java
  ssl/src/main/java9/org/wildfly/security/ssl/JDKSpecific.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLConfiguratorImplTest.java
Labels: 1.10.x, Maintenance

#1402 [ELY-1974] Correct the package names of the hard coded class names re…
  provider/util/src/main/java/org/wildfly/security/provider/util/ProviderFactory.java
Labels: +1 FJ, 1.x

#1401 [ELY-1970] Ensure multiple service implementations of the same type are aggregated.
  wildfly-elytron/pom.xml
Labels: +1 FJ, 1.x

#1405 [ELY-1976] Elytron provider not being used with credential store and SASL authentication on the Client Side
  auth/client/src/main/java/org/wildfly/security/auth/client/CredentialStoreFactory.java
  credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
  tests/base/src/test/java/org/wildfly/security/auth/client/CredentialStoreSaslAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
  tests/base/src/test/resources/org/wildfly/security/auth/client/wildfly-credential-sasl-config.xml
Labels: +1 DV, +1 FJ, 1.x

#1411 Add a blog post on the new security features we will be working on during the WildFly 21 development phase
  _layouts/community.html
  _posts/2020-06-11-planned-security-features-for-wildfly-21.adoc
Labels: website

#1412 Update roadmap link
  _layouts/community.html
Labels: website

#1409 Add a blog post that covers Elytron's filesystem realms, credential stores and SASL authentication with EJBs
  _data/authors.yaml
  _posts/2020-06-11-advanced-ejb-security.adoc
Labels: website

#1417 Add blog post about regex-role-mapper
  _posts/2020-06-15-regex-role-mapper.adoc
Labels: website

#1413 [ELY-1997] Upgrade jboss-logmanager to 2.1.16.Final
  pom.xml
Labels: +1 DAL, +1 FJ, 1.x

#1421 [ELY-1999] Upgrade JBoss Threads to 2.3.5.Final
  pom.xml
Labels: +1 DAL, +1 FJ, 1.x

#1416 [ELY-1982] TLS with BCJSSE Provider does not work
  ssl/src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
Labels: +1 DAL, +1 FJ, 1.x

#1420 [ELY-2000] Additional TRACE logging where GssCredential obtained from CredentialCallback.
  sasl/gssapi/src/main/java/org/wildfly/security/sasl/gssapi/GssapiClient.java
Labels: +1 FJ, 1.x

#1415 [ELY-1984] Add a wrapper HttpServerAuthenticationMechanismFactory that sets the peer address using the current authentication request
  http/util/src/main/java/org/wildfly/security/http/util/SocketAddressCallbackServerMechanismFactory.java
Labels: +1 DAL, 1.x

#1422 [ELY-2003] Upgrading jboss-logmanager to 2.1.17.Final
  pom.xml
Labels: +1 FJ, 1.x

#1423 Add a blog post introducing Intrusion Detection system
  _data/authors.yaml
  _posts/2020-06-30-architectural-overview-intrusion-detection-system.adoc
Labels: website
