Repository wildfly-security/wildfly-elytron, pull requests merged in 2020-11, with the labels that each got.

#1451 [ELY-2029] Checking String equality using != in SimpleDirContextFactoryBuilder
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
Labels: +1 DAL, +1 DV

#1450 [ELY-2028] Resource leak in JaspiAuthenticationContext
  auth/jaspi/src/main/java/org/wildfly/security/auth/jaspi/impl/JaspiAuthenticationContext.java
Labels: +1 DAL, +1 DV

#1446 [ELY-2025] Resource leak in ElytronXmlParser.
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
Labels: +1 DAL, +1 DV

#1454 [ELY-2030] Possible NullPointerException in FileSystemRealmCommand
  tool/src/main/java/org/wildfly/security/tool/FileSystemRealmCommand.java
Labels: +1 DAL, 1.x

#1442 [ELY-2023] Elytron ClientCertAuthenticationMechanism does not work when using a web proxy
  auth/server/base/src/main/java/org/wildfly/security/auth/callback/PrincipalAuthorizeCallback.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
  http/cert/src/main/java/org/wildfly/security/http/cert/ClientCertAuthenticationMechanism.java
Labels: +1 DAL, +1 FJ, Maintenance

#1449 [1.10.x] [ELY-2026] Use reflection to pass through the new methods if they are now available on the SSLEngine, SSLParameters, and SSLSocket APIs.
  ssl/src/main/java/org/wildfly/security/ssl/JDKSpecific.java
  ssl/src/main/java/org/wildfly/security/ssl/SSLConfiguratorImpl.java
Labels: Critical, Maintenance

#1460 ELY-2031 Allow loose credential matches in IdentityCredentials.Many
  auth/server/base/src/main/java/org/wildfly/security/auth/server/IdentityCredentials.java
  tests/base/src/test/java/org/wildfly/security/auth/server/IdentityCredentialsTest.java
Labels: Maintenance

#1461 ELY-2036 Support DigestSaslServer.getNegotiatedProperty() for QOP and STRENGTH
  sasl/digest/src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
  sasl/digest/src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
  tests/base/src/test/java/org/wildfly/security/sasl/digest/CompatibilityServerTest.java
Labels: Maintenance

#1463 [1.10.x] [ELY-2045] Update tests to use SHA256withRSA instead of SHA1withRSA.
  tests/base/src/test/java/org/wildfly/security/auth/client/MaskedPasswordSSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
  tests/base/src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
  tests/base/src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java
  tests/base/src/test/java/org/wildfly/security/sasl/entity/EntityTest.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/util/PemTest.java
  tests/base/src/test/resources/org/wildfly/security/ssl/ocsp-responder.xml
Labels: +1 DV, +1 FJ, Critical, Maintenance

#1464 [ELY-2045] Update tests to use SHA256withRSA instead of SHA1withRSA.
  tests/base/src/test/java/org/wildfly/security/auth/client/MaskedPasswordSSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
  tests/base/src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
  tests/base/src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java
  tests/base/src/test/java/org/wildfly/security/sasl/entity/EntityTest.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/ssl/TLS13AuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/util/PemTest.java
  tests/base/src/test/resources/org/wildfly/security/ssl/ocsp-responder.xml
Labels: +1 DV, +1 FJ
