Repository wildfly-security/wildfly-elytron, pull requests merged in 2020-07, with the labels that each got.

#1424 [ELY-2004] Remove handling of delegated credential as it is repeated as soon as `authorizeSrcName(...)` is called.
  http/spnego/src/main/java/org/wildfly/security/http/spnego/SpnegoAuthenticationMechanism.java
Labels: +1 FJ, 1.x

#1425 Various JACC Enhancements / Clean Up
  jacc/pom.xml
  jacc/src/main/java/org/wildfly/security/authz/jacc/DelegatingPolicyContextHandler.java
  jacc/src/main/java/org/wildfly/security/authz/jacc/RoleToGroupMapper.java
  jacc/src/main/java/org/wildfly/security/authz/jacc/SecurityActions.java
  jacc/src/main/java/org/wildfly/security/authz/jacc/SecurityIdentityHandler.java
  jacc/src/main/java/org/wildfly/security/authz/jacc/SubjectPolicyContextHandler.java
  jacc/src/main/java/org/wildfly/security/authz/jacc/SubjectUtil.java
  jacc/src/test/java/org/wildfly/security/authz/jacc/AbstractAuthorizationTestCase.java
  jacc/src/test/java/org/wildfly/security/authz/jacc/ElytronPolicyEnforcementTest.java
  jacc/src/test/java/org/wildfly/security/authz/jacc/LinkPolicyConfigurationTest.java
  jacc/src/test/java/org/wildfly/security/authz/jacc/PolicyConfigurationTest.java
  jacc/src/test/java/org/wildfly/security/authz/jacc/SecurityIdentityRule.java
  jacc/src/test/java/org/wildfly/security/authz/jacc/StandardPolicyEnforcementTest.java
  jacc/src/test/resources/org/wildfly/security/authz/jacc/clear.properties
  tests/base/pom.xml
Labels: +1 FJ, 1.x

#1374 [ELY-1932] Support for multiple realms - Distributed Identities
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/DistributedSecurityRealm.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
  tests/base/src/test/java/org/wildfly/security/auth/realm/DistributedSecurityRealmTest.java
Labels: +1 DV, +1 FJ, 1.x, Feature Request

#1426 [ELY-2009] Remove loadedIdentities from PrincipalDistributedIdentity since it is unused and correct PrincipalDistributedIdentity#dispose
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/DistributedSecurityRealm.java
Labels: +1 DAL, +1 DV, 1.x

#1347 [ELY-1879] Support SSH Authentication for Git persistence
  ELY_Messages.txt
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronMessages.java
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/client/src/main/resources/schema/elytron-client-1_6.xsd
  auth/client/src/test/java/org/wildfly/security/auth/client/OpenSSHKeysParserTest.java
  auth/client/src/test/resources/org/wildfly/security/auth/client/README.txt
  auth/client/src/test/resources/org/wildfly/security/auth/client/test-wildfly-config-openssh-keys.xml
  auth/util/pom.xml
  auth/util/src/main/java/org/wildfly/security/auth/util/ElytronFilePasswordProvider.java
  auth/util/src/main/java/org/wildfly/security/auth/util/ElytronMessages.java
  credential/base/src/main/java/org/wildfly/security/credential/SSHCredential.java
  pom.xml
  tests/base/pom.xml
  tests/base/src/test/resources/schema/wrapped-elytron-client-1_6.xsd
  tool/pom.xml
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
  tool/src/test/resources/ssh-keys/README.txt
  tool/src/test/resources/ssh-keys/id_ecdsa
  tool/src/test/resources/ssh-keys/id_ecdsa_pkcs
  tool/src/test/resources/ssh-keys/id_ecdsa_pkcs.pub
  x500/cert/base/pom.xml
  x500/cert/base/src/main/java/org/wildfly/security/pem/Pem.java
  x500/cert/base/src/main/java/org/wildfly/security/x500/cert/_private/ElytronMessages.java
Labels: +1 DAL, +1 FJ, 1.x, Feature Request

#1428 [ELY-2011] Upgrade jboss-threads to 2.3.6.Final
  pom.xml
Labels: +1 FJ, 1.x

#1340 [ELY-1891] Introduce RESTEasy integration with WildFly Elytron - Auth…
  auth/client/pom.xml
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java
  auth/client/src/main/java/org/wildfly/security/auth/client/CredentialStoreFactory.java
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/client/src/main/java/org/wildfly/security/auth/client/MatchHostRule.java
  auth/client/src/main/java/org/wildfly/security/auth/client/MatchRule.java
  auth/client/src/main/java/org/wildfly/security/auth/client/ModuleLoader.java
  auth/client/src/main/java/org/wildfly/security/auth/client/PeerIdentity.java
  auth/client/src/main/java/org/wildfly/security/auth/client/_private/ElytronMessages.java
  auth/client/src/main/java/org/wildfly/security/auth/client/spi/RESTEasyClientConfigProviderImpl.java
  wildfly-elytron/pom.xml
Labels: +1 DAL, +1 FJ, 1.x, Feature Request

#1429 [ELY-2013] Upgrade JBoss Threads to 2.4.0.Final
  pom.xml
Labels: +1 FJ, 1.x

#1430 Add a blog post introducing rule engine and blacklist IP dump of IDS
  _posts/2020-07-27-introduction-rule-engine-and-blacklist-dump.adoc
Labels: website
