Repository wildfly-security/wildfly-elytron, pull requests merged in 2021-07, with the labels that each got.

#1538 Blog post - Using Galleon to provision the Keycloak client adators.
  .gitignore
  _posts/2021-07-01-galleon-cli-keycloak.adoc
Labels: website

#1550 [ELY-2148] Upgrade MicroProfile JWT API to 1.2.1
  pom.xml
Labels: +1 FJ

#1535 [ELY-2132] Cleanup dead code and unused variable in ElytronXmlParser.
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
Labels: +1 DAL

#1547 [ELY-2143] The constructor of CachingSecurityRealm is not correctly implemented.
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/CachingModifiableSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/CachingSecurityRealm.java
Labels: +1 FJ

#1539 [ELY-2137] Possible NullPointerException in AuthenticationConfiguration
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
Labels: +1 DV, +1 FJ

#1521 ELY-2120 Avoid an NPE in ServerAuthenticationContext when the peer's IP address is not known
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Labels: Maintenance

#1549 [ELY-2147] Harden ScramServer against timing attacks
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramServer.java
Labels: +1 FJ

#1551 [ELY-2147] Harden ScramServer against timing attacks
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramServer.java
Labels: Maintenance

#1553 [ELY-2154] Add javadoc for org.wildfly.security.password.spec.Encoding
  credential/base/src/main/java/org/wildfly/security/password/spec/Encoding.java
Labels: +1 DV, +1 FJ

#1554 [ELY-2152] Add link to Elytron Website in Elytron README
  README.md
Labels: +1 FJ

#1555 [ELY-2153] Add parameter validation to LdapSecurityRealm
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
Labels: +1 DV, +1 FJ

#1556 [ELY-2157] Add parameter validation for AggregateSecurityRealm
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java
Labels: +1 FJ

#1557 [ELY-2156] Add parameter validation for FailoverSecurityRealm
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FailoverSecurityRealm.java
Labels: +1 FJ

#1558 ELY-2189 Token Realm Validator timeouts
  auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwkManager.java
  auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
  auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/OAuth2IntrospectValidator.java
Labels: +1 FJ

#1559 Add a blog post that gives a recap of Open Source Day
  _posts/2021-07-22-open-source-day-summer-recap.adoc
  _sass/main.scss
  assets/images/posts/SummerOpenSourceDay2021.png
Labels: website
