Repository wildfly-security/wildfly-elytron, pull requests merged in 2021-01, with the labels that each got.

#1477 [ELY-2063] Masked password interface contains 8 algorithms unavailable on IBM JDK 8
  credential/base/src/main/java/org/wildfly/security/password/interfaces/MaskedPassword.java
  password/impl/src/test/java/org/wildfly/security/password/impl/MaskedPasswordTest.java
Labels: +1 DAL, +1 FJ

#1476 [ELY-2060] Move Certificate Authority set up to re-usable tool.
  sasl/external/src/test/java/org/wildfly/security/sasl/external/ExternalSaslClientTest.java
  sasl/external/src/test/java/org/wildfly/security/sasl/external/ExternalSaslServerTest.java
  sasl/gssapi/src/test/java/org/wildfly/security/sasl/gssapi/MechanismSelectionTestCase.java
  tests/base/src/test/java/org/wildfly/security/auth/client/MaskedPasswordSSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
  tests/base/src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/digest/CompatibilityClientTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/digest/CompatibilityServerTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/digest/DigestTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/entity/EntityTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/gs2/Gs2SuiteChild.java
  tests/base/src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientV10Test.java
  tests/base/src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientV11Test.java
  tests/base/src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/otp/OTPTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/plain/PlainTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/scram/BasicScramSelfTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/scram/ScramClientCompatibilityTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/scram/ScramServerCompatibilityTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/AnonymousTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/LocalUserTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslFactoriesApiTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/ssl/TLS13AuthenticationTest.java
  tests/base/src/test/resources/org/wildfly/security/auth/client/wildfly-masked-password-ssl-config-v1_4.xml
  tests/base/src/test/resources/org/wildfly/security/ssl/ocsp-responder.xml
  tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_1.xml
  tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_5.xml
  tests/common/src/test/java/org/wildfly/security/sasl/test/SaslTestUtil.java
  tests/common/src/test/java/org/wildfly/security/ssl/test/util/CAGenerationTool.java
Labels: +1 FJ

#1467 ELY-2050 Update bouncycastle to 1.67
  pom.xml
Labels: +1 DAL

#1419 Add a blog post about case-principal-transformer
  _posts/2021-01-12-case-principal-transformer.adoc
Labels: website

#1478 Add a blog post on automatic self-signed certificate generation
  _data/navigation.yml
  _layouts/community.html
  _posts/2021-01-14-auto-self-signed-certificate-generation.adoc
Labels: website

#1481 Add a blog post that gives an overview of the new security features that we will be working on
  _layouts/community.html
  _posts/2021-01-22-planned-security-features-for-wildfly-23.adoc
Labels: website

#1471 [JBEAP-20656] [ELY-1976] Elytron provider not being used with credential store and SASL authentication on the client side
  auth/client/src/main/java/org/wildfly/security/auth/client/CredentialStoreFactory.java
  credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
  tests/base/src/test/java/org/wildfly/security/auth/client/CredentialStoreSaslAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
  tests/base/src/test/resources/org/wildfly/security/auth/client/wildfly-credential-sasl-config.xml
Labels: +1 FJ, 1.10.x

#1480 [ELY-2043] Improving http-server-mechanism-factory logging
  http/util/src/main/java/org/wildfly/security/http/util/AggregateServerMechanismFactory.java
Labels: +1 FJ, 1.x

#1479 [ELY-2069] JWT token validation uses int instead of long for the dates:exp (expiration) and nbf
  auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
Labels: +1 FJ, 1.x

#1482 [ELY-2071] Upgrade Apache DS to version AM26
  pom.xml
  tests/base/src/test/java/org/wildfly/security/apacheds/LdapService.java
  tests/base/src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
  tests/base/src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java
  tests/base/src/test/java/org/wildfly/security/ldap/ModifiabilitySuiteChild.java
  tests/base/src/test/java/org/wildfly/security/sasl/gssapi/TestKDC.java
Labels: +1 FJ, 1.x

#1470 [ELY-2053] key-store-masked-password needs the elytron provider to be manually registered
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/client/src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
Labels: +1 FJ, 1.x
