Repository wildfly-security/wildfly-elytron, pull requests merged in 2021-10, with the labels that each got.

#1577 [ELY-2151] fix typos in website
  docs.adoc
Labels: +1 DV

#1573 [ELY-2155] Add parameter validation for KeyStoreBackedSecurityRealm
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/KeyStoreBackedSecurityRealm.java
  tests/base/src/test/java/org/wildfly/security/sasl/entity/EntityTest.java
Labels: +1 FJ, +1 DV

#1574 [ELY-2217] Upgrade jose4j library to 0.7.9
  pom.xml
Labels: +1 FJ, +1 DV

#1576 [ELY-2216] Upgrade FasterXML/jackson to 2.11.4
  pom.xml
Labels: +1 FJ, +1 DV

#1578 [ELY-2176] Add parameter validation in QueryBuilder
  auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/QueryBuilder.java
Labels: +1 FJ, +1 DV

#1579 [ELY-2158] Added parameter validation for DistributedSecurityRealm
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/DistributedSecurityRealm.java
Labels: +1 FJ, +1 DV

#1580 [ELY-2150] Added parameter validation in StringEnumeration class
  util/src/main/java/org/wildfly/security/util/StringEnumeration.java
Labels: +1 FJ, +1 DV

#1581 [ELY-2149] Enhance logging for silent BASIC authentication mechanism
  http/basic/src/main/java/org/wildfly/security/http/basic/BasicAuthenticationMechanism.java
Labels: +1 FJ, +1 DV

#1582 [ELY-2183] The vault command prompts for the password twice
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
Labels: +1 FJ, +1 DV

#1583 [ELY-2218] Upgrade Microprofile JWT API to 1.2.2
  pom.xml
Labels: +1 FJ, +1 DV

#1584 [ELY-2219] Update wildfly-elytron/tool README to not include info about github issues for tool
  tool/README.md
Labels: +1 FJ, +1 DV

#1585 [ELY-2161] Add parameter validation to the builder setters in LegacyP…
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
Labels: +1 FJ, +1 DV

#1586 [ELY-2224] Create a CONTRIBUTING.md file for new contributors
  CONTRIBUTING.md
  assets/images/clone.png
  assets/images/fork.jpg
  assets/images/jira.png
Labels: +1 FJ, +1 DV

#1587 [ELY-2223] Update the Ubuntu version that gets used by GitHub Actions
  .github/workflows/pr-ci.yaml
  pom.xml
Labels: +1 FJ

#1571 ELY-2212 Support private RSA keys in PEM parser
  keystore/pom.xml
  keystore/src/main/java/org/wildfly/security/keystore/KeyStoreUtil.java
  keystore/src/test/java/org/wildfly/security/keystore/KeyStoreUtilTest.java
  tests/base/src/test/java/org/wildfly/security/util/PemTest.java
  x500/cert/base/src/main/java/org/wildfly/security/pem/Pem.java
Labels: +1 FJ, +1 DV

#1590 [ELY-2160] Add parameter validation in RegexNameRewriter and RegexNameValidatingRewriter
  auth/util/src/main/java/org/wildfly/security/auth/util/RegexNameRewriter.java
  auth/util/src/main/java/org/wildfly/security/auth/util/RegexNameValidatingRewriter.java
Labels: +1 FJ, +1 DV
