Repository wildfly-security/wildfly-elytron, pull requests merged in 2021-11, with the labels that each got.

#1602 [ELY-1850] CredentialStore API missing ability to check alias types
  credential/store/src/main/java/org/wildfly/security/credential/store/CredentialStore.java
  credential/store/src/main/java/org/wildfly/security/credential/store/CredentialStoreSpi.java
  credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/test/java/org/wildfly/security/tool/AbstractCommandTest.java
  tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1626 [ELY-2251] Create a separate shaded jar for elytron-tool for testing purposes
  tool/pom.xml
Labels: Maintenance

#1617 [ELY-2200] Update org.apache.sshd:sshd-common:2.3.0 to 2.7.0
  pom.xml
Labels: Maintenance

#1625 [ELY-2256] Upgrade to RestEasy Client 4.7.2.Final and use dependency management in parent.
  auth/client/pom.xml
  pom.xml
Labels: +1 FJ

#1624 [ELY-2255] Upgrade net.minidev:json-smart to 2.4.7.
  pom.xml
Labels: +1 FJ

#1628 [ELY-2259] Fix version of wildfly-elytron-http-stateful-basic to be compatible with parent pom
  http/stateful-basic/pom.xml
Labels: +1 FJ
