Repository wildfly-security/wildfly-elytron, pull requests merged in 2021-03, with the labels that each got.

#1494 [ELY-2098] Webservices client should use currently configured and not previously configured authentication context
  auth/client/src/main/java/org/wildfly/security/auth/client/spi/WebServicesClientConfigProviderImpl.java
Labels: +1 DAL, +1 FJ, Critical

#1495 [ELY-2099] Ensure only WildFly Elytron classes are included in the shaded JAR
  wildfly-elytron/pom.xml
Labels: +1 DAL, 1.x

#1496 Revert "[ELY-2099] Ensure only WildFly Elytron classes are included in the shaded JAR"
  wildfly-elytron/pom.xml
Labels: +1 DAL, 1.x, Critical

#1500 [ELY-2104] two calls to introspection endpoint for one request with JWT
  auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/TokenSecurityRealm.java
Labels: +1 DAL, +1 FJ, 1.x

#1485 [ELY-2069] JWT token validation uses int instead of long for the dates: exp (expiration) and nbf
  auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
Labels: Maintenance

#1484 [ELY-2053] key-store-masked-password needs the elytron provider to be manually registered
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/client/src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
Labels: Maintenance

#1502 Add a blog post describing how to use encrypted expressions in WildFly 23.
  _data/authors.yaml
  _posts/2021-03-19-wildfly-encrypted-expressions.adoc
Labels: website

#1503 Aggregate PR
  _data/navigation.yml
  _layouts/community.html
  _posts/2021-03-19-automatic-registration-of-client-side-jvm-wide-default-sslcontext.adoc
  _posts/2021-03-19-new-security-features-in-wildfly-23.adoc
  _posts/2021-03-19-new-ssl-features.adoc
  _posts/2021-03-19-normalization-of-EJB-principal-propagation.adoc
  _posts/2021-03-19-sslcontext-delegation-to-alternate-instances-based-on-peer.adoc
  _posts/2021-03-19-upcoming-hash-encodings.adoc
Labels: website

#1506 [ELY-2109] Upgrade JBoss LogManager to 2.1.18.Final.
  pom.xml
Labels: +1 FJ, 1.x

#1505 [ELY-2108] Subject private credentials have zeroes when passed to elytron-enabled datasource
  mechanism/http/src/main/java/org/wildfly/security/mechanism/http/UsernamePasswordAuthenticationMechanism.java
  tests/base/src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
Labels: +1 DAL, +1 FJ, 1.x
