Repository wildfly-security/wildfly-elytron, pull requests merged in 2021-06, with the labels that each got.

#1530 [ELY-2071] / [ELY-2073] Revert ELY-2071 and ELY-2073
  pom.xml
  tests/base/src/test/java/org/wildfly/security/apacheds/LdapService.java
  tests/base/src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
  tests/base/src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java
  tests/base/src/test/java/org/wildfly/security/ldap/ModifiabilitySuiteChild.java
  tests/base/src/test/java/org/wildfly/security/sasl/gssapi/TestKDC.java
Labels: +1 FJ

#1529 [ELY-2117] SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate) on IBM JDK after ELY-2026
  ssl/src/main/java/org/wildfly/security/ssl/ConfiguredSSLServerSocketFactory.java
  ssl/src/main/java/org/wildfly/security/ssl/ConfiguredSSLSocketFactory.java
Labels: +1 FJ

#1524 [ELY-2123] secret-key-credential-store does not make parent directories when being created
  credential/store/src/main/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStore.java
  credential/store/src/test/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStoreTest.java
Labels: +1 DV

#1522 [ELY-2102] Fix slf4j warning messages when using Elytron Tool
  pom.xml
  tool/pom.xml
Labels: +1 FJ

#1458 [ELY-2024] Elytron server-ssl-context allowed protocols
  ssl/src/main/java/org/wildfly/security/ssl/Protocol.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLv2HelloAuthenticationTest.java
  tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_6.xml
Labels: +1 DV, +1 FJ, 1.x, Feature Request, INSUFFICIENT ACKS

#1469 [ELY-2033] Certificate Revocation Lists
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/client/src/main/resources/schema/elytron-client-1_7.xsd
  ssl/src/main/java/org/wildfly/security/ssl/X509RevocationTrustManager.java
  tests/base/pom.xml
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
  tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_7.xml
  tests/base/src/test/resources/schema/wrapped-elytron-client-1_7.xsd
  tests/common/src/test/java/org/wildfly/security/ssl/test/util/CAGenerationTool.java
Labels: +1 DV, +1 FJ, 1.x, Feature Request, INSUFFICIENT ACKS

#1531 [ELY-2088] Revert "[ELY-1626] Temporary commit to preserve API compatibility with the WildFly integration."
  http/sso/src/main/java/org/wildfly/security/http/util/sso/ImmutableSingleSignOn.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnManager.java
Labels: +1 DV, +1 FJ

#1532 [ELY-2127] Add client side TRACE logging after successful authentication
  sasl/base/src/main/java/org/wildfly/security/sasl/util/AbstractSaslParticipant.java
  sasl/oauth2/src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClient.java
  sasl/oauth2/src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslServer.java
  sasl/plain/src/main/java/org/wildfly/security/sasl/plain/PlainSaslClient.java
  sasl/scram/src/main/java/org/wildfly/security/sasl/scram/ScramSaslClient.java
  sasl/scram/src/main/java/org/wildfly/security/sasl/scram/ScramSaslServer.java
Labels: +1 FJ

#1533 [ELY-2131] Possible NullPointerException in JwtValidator when validating token with jku claim and SSL is not configured.
  auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
Labels: +1 DV, +1 FJ

#1537 Added a blog post about authenticating ejb-over-http
  _data/authors.yaml
  _posts/2021-06-14-ejb-over-http.adoc
Labels: website

#1523 Add blog post about securing of WildFly CLI with Keycloak
  _posts/2021-06-15-secure-wildfly-cli-with-keycloak.adoc
  assets/images/posts/2021-06-15-secure-wildfly-cli-with-keycloak-RealmRoles.png
  assets/images/posts/2021-06-15-secure-wildfly-cli-with-keycloak-WildFlyClientApp.png
Labels: website

#1472 Add a blog post about configuring SSL using certificate revocation lists
  _posts/2021-06-18-ssl-certificate-revocation-list.adoc
Labels: website

#1543 Adding information about getting started with Elytron Web and WildFly OpenSSL
  getting-started-for-developers.adoc
Labels: website

#1540 [ELY-2138] / [ELY-2139] Logging component upgrades.
  pom.xml
Labels: +1 FJ

#1462 Add blog post about configuring SSLv2Hello
  _posts/2021-06-21-oneway-sslv2hello.adoc
Labels: hold, website

#1443 Add a blog post about hash-encodings and hash-charsets
  _posts/2021-06-24-hash-charsets-encodings.adoc
Labels: hold, website

#1548 [ELY-2145] Default platform encoding used in OAuth2IntrospectValidator and OAuth2CredentialSource.
  auth/client/src/main/java/org/wildfly/security/credential/source/OAuth2CredentialSource.java
  auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/OAuth2IntrospectValidator.java
Labels: +1 FJ

#1545 [ELY-2142] Elytron Tool: Default platform encoding used in VaultCommand.
  tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
Labels: +1 FJ

#1542 [ELY-2140] Elytron Tool: Mask command will fail when secret is not provided.
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/main/java/org/wildfly/security/tool/MaskCommand.java
Labels: +1 FJ

#1544 [ELY-2141] Elytron Tool: Default platform encoding used in Command.
  tool/src/main/java/org/wildfly/security/tool/Command.java
Labels: +1 FJ
