Repository wildfly-security/wildfly-elytron, pull requests merged in 2021-12, with the labels that each got.

#1630 [ELY-2195] Use daemon threads in default ScheduledExecutorService
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
Labels: +1 FJ, 1.x

#1642 [ELY-2278] Add 1.17.x branch to pr-ci.yaml for Github Actions
  .github/workflows/pr-ci.yaml
Labels: +1 FJ, +1 DV

#1644 [ELY-2262] Added spaces between each tag
  _layouts/blog.html
  _layouts/post.html
Labels: +1 FJ

#1641 [1.17] ELY-2271 + ELY-2272
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/CachingModifiableSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/CachingSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
  auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/JdbcSecurityRealm.java
  auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/QueryBuilder.java
  auth/realm/jdbc/src/test/java/org/wildfly/security/auth/realm/jdbc/AttributeMappingTest.java
  auth/realm/jdbc/src/test/java/org/wildfly/security/auth/realm/jdbc/AuthorizationIdentityTest.java
  auth/realm/jdbc/src/test/java/org/wildfly/security/auth/realm/jdbc/DataSourceRule.java
  auth/realm/jdbc/src/test/java/org/wildfly/security/auth/realm/jdbc/PasswordSupportTest.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/IdentityCredentials.java
  credential/base/src/main/java/org/wildfly/security/credential/Credential.java
  http/basic/src/main/java/org/wildfly/security/http/basic/BasicMechanismFactory.java
  http/digest/src/main/java/org/wildfly/security/http/digest/DigestMechanismFactory.java
  http/external/src/main/java/org/wildfly/security/http/external/ExternalMechanismFactory.java
  tests/base/src/test/java/org/wildfly/security/apacheds/CryptCompatibilityTest.java
  tests/base/src/test/java/org/wildfly/security/auth/FileSystemSecurityRealmTest.java
  tests/base/src/test/java/org/wildfly/security/auth/KeyStoreBackedSecurityRealmTest.java
  tests/base/src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
  tests/base/src/test/java/org/wildfly/security/auth/realm/DistributedSecurityRealmTest.java
  tests/base/src/test/java/org/wildfly/security/auth/realm/cache/ModifiableSecurityRealmIdentityCacheTest.java
  tests/base/src/test/java/org/wildfly/security/auth/realm/cache/SecurityRealmIdentityCacheTest.java
  tests/base/src/test/java/org/wildfly/security/auth/server/IdentityCredentialsTest.java
  tests/base/src/test/java/org/wildfly/security/auth/server/IdentitySwitchingTest.java
  tests/base/src/test/java/org/wildfly/security/auth/server/ServerUtils.java
  tests/base/src/test/java/org/wildfly/security/credential/store/CredentialStoreBuilder.java
  tests/base/src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
  tests/base/src/test/java/org/wildfly/security/digest/Sha512_256MessageDigestTest.java
  tests/base/src/test/java/org/wildfly/security/http/HttpAuthenticatorTest.java
  tests/base/src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
  tests/base/src/test/java/org/wildfly/security/keystore/PasswordFileKeyStoreTest.java
  tests/base/src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java
  tests/base/src/test/java/org/wildfly/security/ldap/LdapSecurityRealmIdentityCacheSuiteChild.java
  tests/base/src/test/java/org/wildfly/security/ldap/PasswordSupportSuiteChild.java
  tests/base/src/test/java/org/wildfly/security/sasl/plain/PlainTest.java
Labels: +1 FJ, +1 DV

#1637 Add blog post about upcoming filesystem encryption and integrity features
  _posts/2021-12-17-upcoming-filesystem-encryption-integrity.adoc
Labels: website

#1639 Add blogpost on JAAS realm
  _posts/2021-12-17-jaas-realm.adoc
Labels: website

#1645 Add blog post about upcoming client side default ssl context provider
  _posts/2021-12-17-client-side-jvm-wide-default-sslcontext.adoc
Labels: website

#1640 Add a blog post on OpenID Connect and a release blog post for WildFly 26
  _layouts/community.html
  _posts/2021-12-17-client-side-jvm-wide-default-sslcontext.adoc
  _posts/2021-12-17-new-security-features-wildfly.adoc
  _posts/2021-12-17-securing-wildfly-apps-openid-connect.adoc
  docs.adoc
Labels: website
