Repository wildfly-security/wildfly-elytron, pull requests merged in 2021-02, with the labels that each got.

#1487 [ELY-2068] Upgrade to MicroProfile JWT 1.2
  jwt/pom.xml
  pom.xml
Labels: +1 FJ, 1.x, Critical, Feature Request

#1486 [ELY-1842] / [ELY-2055] / [ELY-2081] / [ELY-2086] SecretKey manipulation and encrypted expression support.
  ELY_Messages.txt
  audit/src/main/java/org/wildfly/security/audit/ElytronMessages.java
  base/src/main/java/org/wildfly/security/WildFlyElytronProvider.java
  credential/store/pom.xml
  credential/store/src/main/java/org/wildfly/security/credential/store/WildFlyElytronCredentialStoreProvider.java
  credential/store/src/main/java/org/wildfly/security/credential/store/_private/ElytronMessages.java
  credential/store/src/main/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStore.java
  credential/store/src/test/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStoreTest.java
  encryption/pom.xml
  encryption/src/main/java/org/wildfly/security/encryption/CipherUtil.java
  encryption/src/main/java/org/wildfly/security/encryption/Common.java
  encryption/src/main/java/org/wildfly/security/encryption/ElytronMessages.java
  encryption/src/main/java/org/wildfly/security/encryption/SecretKeyUtil.java
  encryption/src/main/java/org/wildfly/security/encryption/package-info.java
  encryption/src/test/java/org/wildfly/security/encryption/CipherUtilTest.java
  encryption/src/test/java/org/wildfly/security/encryption/SecretKeyUtilTest.java
  pom.xml
  tests/base/src/test/java/org/wildfly/security/audit/SyslogAuditEndpointTest.java
  tool/pom.xml
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/main/java/org/wildfly/security/tool/ElytronTool.java
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
  tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
  tool/src/test/java/org/wildfly/security/tool/SecretKeyCommandTest.java
  wildfly-elytron/pom.xml
Labels: +1 DV, +1 FJ, 1.x, Critical, Feature Request

#1483 [ELY-1626] Programmatic web authentication (HttpServletRequest.login()) does not trigger sso
  auth/server/base/src/main/java/org/wildfly/security/cache/CachedIdentity.java
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/SecurityIdentityServerMechanismFactory.java
  auth/server/http/src/main/java/org/wildfly/security/auth/server/http/SecurityIdentityServerMechanismFactory.java
  http/base/src/main/java/org/wildfly/security/http/HttpAuthenticator.java
  http/base/src/main/java/org/wildfly/security/http/impl/BaseHttpServerRequest.java
  http/base/src/main/java/org/wildfly/security/http/impl/package-info.java
  http/cert/src/main/java/org/wildfly/security/http/cert/ClientCertAuthenticationMechanism.java
  http/form/src/main/java/org/wildfly/security/http/form/FormAuthenticationMechanism.java
  http/spnego/src/main/java/org/wildfly/security/http/spnego/SpnegoAuthenticationMechanism.java
  http/sso/pom.xml
  http/sso/src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOn.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnManager.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSession.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSessionFactory.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/ImmutableSingleSignOn.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/ProgrammaticSingleSignOnCache.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnConfiguration.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnManager.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnServerMechanismFactory.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnSession.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnSessionFactory.java
  http/util/src/main/java/org/wildfly/security/http/util/SetMechanismInformationMechanismFactory.java
  http/util/src/main/java/org/wildfly/security/http/util/SimpleHttpServerCookie.java
  http/util/src/main/java/org/wildfly/security/http/util/SocketAddressCallbackServerMechanismFactory.java
Labels: +1 DV, +1 FJ, Critical

#1492 [ELY-2092] Removal of an entry of a specific type is corrupting the cache of entries.
  credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
  credential/store/src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
Labels: +1 FJ, 1.x, Critical

#1491 [ELY-2091] Wrap any error reported decoding the Base64 token.
  encryption/src/main/java/org/wildfly/security/encryption/CipherUtil.java
  encryption/src/main/java/org/wildfly/security/encryption/ElytronMessages.java
  encryption/src/main/java/org/wildfly/security/encryption/SecretKeyUtil.java
Labels: +1 FJ, 1.x, Critical

#1489 [ELY-1783] Update getting started guide in README
  README.md
Labels: +1 FJ, 1.x

#1490 [ELY-2090] Evidence is not used when getting realm mapping in ServerAuthenticationContext#assignName
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
  tests/base/src/test/java/org/wildfly/security/auth/server/CustomRealmMapperTest.java
Labels: +1 FJ, 1.x

#1493 [ELY-2093] / [ELY-2094] / [ELY-2095] Additional tests and minor fixes.
  credential/store/src/main/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStore.java
  credential/store/src/test/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStoreTest.java
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/test/java/org/wildfly/security/tool/SecretKeyCommandTest.java
Labels: +1 DV, +1 FJ
