Repository wildfly-security/wildfly-elytron, pull requests merged in 2022-03, with the labels that each got.

#1675 ELY-2308: Fix digest authentication for requests with encoded query parameters
  http/digest/src/main/java/org/wildfly/security/http/digest/DigestAuthenticationMechanism.java
  tests/base/src/test/java/org/wildfly/security/http/digest/DigestAuthenticationMechanismTest.java
Labels: +1 FJ, +1 DV

#1682 [ELY-2315] Digest authentication fails for encoded paths
  http/digest/src/main/java/org/wildfly/security/http/digest/DigestAuthenticationMechanism.java
  tests/base/src/test/java/org/wildfly/security/http/digest/DigestAuthenticationMechanismTest.java
Labels: +1 FJ

#1666 ELY-2297 Wrong path for Setup the JBoss Maven Repository.
  README.md
Labels: +1 DV

#1684 ELY-2322 Duplicate dependency in auth/client/pom.xml
  auth/client/pom.xml
Labels: +1 FJ, +1 DV
