Repository wildfly-security/wildfly-elytron, pull requests merged in 2022-04, with the labels that each got.

#1694 [ELY-2330] Community users should use 'Start Progress' instead of 'Assign to me'
  CONTRIBUTING.md
  assets/images/jira_start_progress.png
Labels: +1 FJ

#1672 [ELY-2304] Location is required even for non-filebased type e.g. PKCS11
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
Labels: +1 FJ, +1 DV, Maintenance

#1697 [ELY-2331] Upgrade jackson version to 2.13.1
  pom.xml
Labels: +1 FJ, +1 DV

#1691 [ELY-2328] Remove the JWT module as this is split out to wildfly-elytron-mp.
  jwt/pom.xml
  jwt/src/main/java/org/wildfly/security/mp/jwt/JWTCDIExtension.java
  jwt/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  pom.xml
  wildfly-elytron/pom.xml
Labels: +1 FJ, Critical, +1 DV
