Repository wildfly-security/wildfly-elytron, pull requests merged in 2022-11, with the labels that each got.

#1831 [ELY-2465] JsonSerialization#createObjectNode should throw its exception using ElytronMessages
  ELY_Messages.txt
  jose/util/pom.xml
  jose/util/src/main/java/org/wildfly/security/jose/util/JsonSerialization.java
  jose/util/src/main/java/org/wildfly/security/jose/util/_private/ElytronMessages.java
Labels: hacktoberfest-accepted

#1839 Tweak the Hacktoberfest website content to make it general information for new contributors
  _data/navigation.yml
  _layouts/contribute.html
  _layouts/default.html
  _sass/main.scss
  contribute.adoc
  index.md
Labels: website

#1840 ELY-2463 Add Override annotation to OneTimePassword#getParameterSpec
  credential/base/src/main/java/org/wildfly/security/password/interfaces/OneTimePassword.java
Labels: +1 FJ

#1834 [ELY-2464] RSAPublicJWK#setX509CertificateChain should throw its exception using ElytronMessages
  jose/jwk/src/main/java/org/wildfly/security/jose/jwk/ElytronMessages.java
  jose/jwk/src/main/java/org/wildfly/security/jose/jwk/RSAPublicJWK.java
Labels: +1 FJ, +1 DV
