Repository wildfly-security/wildfly-elytron, pull requests merged in 2022-01, with the labels that each got.

#1635 [ELY-2253] Add a simple implementation of HttpServerCookie
  http/base/src/main/java/org/wildfly/security/http/HttpServerCookie.java
Labels: +1 FJ

#1651 [ELY-2281] Upgrade resteasy-client to 4.7.4.Final
  pom.xml
Labels: +1 FJ, +1 DV

#1652 [ELY-2282] Updated website to add previews on social media to display WildFly Elytron logo
  Gemfile
  _config.yml
  _layouts/default.html
  assets/images/wildfly-elytron-logo.jpg
Labels: +1 FJ, website

#1627 [ELY-2180] Mask command default iteration count, salt dynamically generated
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/main/java/org/wildfly/security/tool/MaskCommand.java
  tool/src/test/java/org/wildfly/security/tool/MaskCommandTest.java
  util/src/main/java/org/wildfly/security/util/PasswordUtil.java
Labels: +1 DV

#1650 [ELY-2280] Remove classes from the org.wildfly.security.auth.client.spi package
  auth/client/pom.xml
  auth/client/src/main/java/org/wildfly/security/auth/client/spi/RESTEasyClientConfigProviderImpl.java
  auth/client/src/main/java/org/wildfly/security/auth/client/spi/WebServicesClientConfigProviderImpl.java
  pom.xml
Labels: +1 DV

#1653 [ELY-2286] make the interfaces OidcHttpFacade.Request/Response and PublicKeyResolver public
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcHttpFacade.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/PublicKeyLocator.java
Labels: +1 FJ, +1 DV

#1654 [ELY-2284] Wildfly OIDC secured App generates a lot of keycloak requests
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfiguration.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcTest.java
Labels: +1 FJ, +1 DV

#1660 [ELY-2290] Update OidcClientConfiguration#resetUrls to handle the case where the provider-url or auth-server-url isn't valid
  http/oidc/src/main/java/org/wildfly/security/http/oidc/ElytronMessages.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfiguration.java
Labels: Critical

#1659 Add a post on multi-tenancy support for OpenID Connect applications
  _posts/2022-01-21-multi-tenancy-support-openid-connect.adoc
Labels: website

#1647 [ELY-2232] Iterate over source resourceAccessValueMap
  http/oidc/src/main/java/org/wildfly/security/http/oidc/AccessToken.java
Labels: Maintenance

#1657 [ELY-2193] Broken pipe exception thrown in testsuite
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Labels: Maintenance

#1649 [ELY-2242] Changed OidcRequestAuthenticator.rewrittenRedirectUri to b…
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientContext.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcRequestAuthenticator.java
Labels: Maintenance

#1661 ELY-2286: interface OidcHttpFacade.Request must be public to allow implementing OidcClientConfigurationResolver.
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcHttpFacade.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/PublicKeyLocator.java
Labels: Maintenance

#1656 [JBEAP-23077] [ELY-2284+ELY-2290] Wildfly OIDC secured App generates a lot of keycloak requests
  http/oidc/src/main/java/org/wildfly/security/http/oidc/ElytronMessages.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfiguration.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcTest.java
Labels: Maintenance

#1658 [ELY-2067] Elytron tool should log a warning that mask password command is not FIPS compliant
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/main/java/org/wildfly/security/tool/MaskCommand.java
Labels: +1 FJ, Maintenance

#1648 [ELY-2234] Add use-realm-role-mappings OIDC configuration setting
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfiguration.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfigurationBuilder.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientContext.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcJsonConfiguration.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcSecurityRealm.java
Labels: Maintenance

#1664 [ELY-2294] Failures in the WFCORE test-suite with branch 1.x
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
  http/basic/src/main/java/org/wildfly/security/http/basic/BasicMechanismFactory.java
  http/digest/src/main/java/org/wildfly/security/http/digest/DigestMechanismFactory.java
  http/external/src/main/java/org/wildfly/security/http/external/ExternalMechanismFactory.java
  tests/base/src/test/java/org/wildfly/security/http/HttpAuthenticatorTest.java
Labels: +1 FJ, +1 DV
