Repository wildfly-security/wildfly-elytron, pull requests merged in 2022-08, with the labels that each got.

#1719 ELY-2351 Fix SCRAM password generation with PKCS#11 (FIPS)
  password/impl/src/main/java/org/wildfly/security/password/impl/ScramDigestPasswordImpl.java
Labels: +1 DV

#1725 [ELY-2358] Option extract-rdn selects the rightmost matching RDN instead of the leftmost one
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
  tests/base/src/test/java/org/wildfly/security/ldap/GroupMappingSuiteChild.java
  tests/base/src/test/resources/ldap/elytron-group-mapping-tests.ldif
Labels: +1 FJ, Maintenance

#1738 Add a post about the upcoming Grace Hopper Open Source Day
  _posts/2022-08-09-top-five-reasons-to-join-elytron-open-source-day.adoc
  _sass/main.scss
  assets/images/posts/OpenSourceDayBanner2022.png
  assets/images/posts/OpenSourceDayProject2022.png
Labels: website

#1733 [ELY-2374] Add support domain_hint query parameter
  http/oidc/src/main/java/org/wildfly/security/http/oidc/Oidc.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcRequestAuthenticator.java
Labels: +1 FJ
