Repository wildfly-security/wildfly-elytron, pull requests merged in 2022-10, with the labels that each got.

#1790 Website updates for Hacktoberfest
  _data/navigation.yml
  _layouts/default.html
  _layouts/hacktoberfest.html
  _sass/main.scss
  hacktoberfest.adoc
  index.md
Labels: website

#1746 [ELY-2370] Move appropriate methods to the JaasRealmIdentity class from JaasSecurityRealm class
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/JaasSecurityRealm.java
Labels: +1 FJ, +1 DV

#1749 [ELY-2368] Add Override annotations to AggregateSecurityRealm
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java
Labels: +1 FJ, +1 DV

#1750 [ELY-2407] Use isEmpty method instead of size method in AcmeClientSpi
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
Labels: +1 FJ, +1 DV

#1751 [ELY-2398] Fix FileSystemEncryptRealmCommand.java so it uses logical OR instead of bitwise OR
  tool/src/main/java/org/wildfly/security/tool/FileSystemEncryptRealmCommand.java
Labels: +1 FJ, +1 DV

#1753 [ELY-2396] Update string to int conversion in ModularCrypt
  credential/base/src/main/java/org/wildfly/security/password/util/ModularCrypt.java
Labels: +1 DV

#1787 [ELY-2403] Declare next on a separate line in DERDecoder#decodeBitStr…
  asn1/src/main/java/org/wildfly/security/asn1/DERDecoder.java
Labels: +1 FJ, +1 DV

#1779 ELY-2420: Update MaskedPasswordImpl to make use of MessageDigest#isEq…
  password/impl/src/main/java/org/wildfly/security/password/impl/MaskedPasswordImpl.java
Labels: +1 DV

#1784 [ELY-2446] Add a test class for RegexNameRewriter
  auth/util/src/test/java/org/wildfly/security/auth/util/RegexNameRewriterTest.java
Labels: +1 FJ, +1 DV

#1793 [ELY-2393] Remove extra header from the Elytron website's documentati…
  _layouts/documentation.html
  docs.adoc
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1794 [ELY-2382] Update message description so no it no longer uses problem…
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
Labels: +1 FJ, +1 DV

#1789 [ELY-2451] Correct a typo in ServerAuthenticationContext.
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Labels: +1 FJ, +1 DV

#1798 [ELY-2367] DefaultSSLContextFromFileWorksAndHasPrecedenceTest, DefaultSSLContextProviderProgrammaticConfigurationTest.java has expected and actual value swaped
  auth/client/src/test/java/org/wildfly/security/auth/client/DefaultSSLContextFromFileWorksAndHasPrecedenceTest.java
  auth/client/src/test/java/org/wildfly/security/auth/client/DefaultSSLContextProviderProgrammaticConfigurationTest.java
Labels: +1 FJ, hacktoberfest-accepted

#1795 [ELY-2392] Fix invalid tags on the Elytron Blogs page
  _posts/2022-04-19-improving-readability-of-alias-commands.adoc
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1801 [ELY-2453] Small updates in RegexNameRewriterTest
  auth/util/src/test/java/org/wildfly/security/auth/util/RegexNameRewriterTest.java
Labels: +1 FJ, hacktoberfest-accepted

#1804 [ELY-2440] Move JaasSecurityRealmTest and its test resources to the same module that JaasSecurityRealm resides in
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/JaasSecurityRealmTest.java
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/TestCallbackHandler.java
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/TestLoginModule.java
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/TestLoginModule2.java
  auth/realm/base/src/test/resources/org/wildfly/security/auth/realm/jaas-login.config
  auth/realm/base/src/test/resources/org/wildfly/security/auth/realm/jaas-login2.config
  tests/base/src/test/resources/org/wildfly/security/auth/jaas-login.config
  tests/base/src/test/resources/org/wildfly/security/auth/jaas-login2.config
Labels: +1 FJ, +1 DV

#1806 [ELY-2313] Update the OIDC tests to use the 19.0.1 version of quay.io/keycloak/keycloak
  http/oidc/src/test/java/org/wildfly/security/http/oidc/KeycloakContainer.java
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1811 [ELY-2469] Update deprecated assertThat method in JACC, credential store and sasl test cases
  credential/store/src/test/java/org/wildfly/security/credential/store/impl/VaultObjectInputStreamTest.java
  jacc/src/test/java/org/wildfly/security/authz/jacc/LinkPolicyConfigurationTest.java
  jacc/src/test/java/org/wildfly/security/authz/jacc/PolicyConfigurationTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslFactoriesApiTest.java
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1802 [ELY-2439] Add a test class for RegexNameValidatingRewriter
  tests/base/src/test/java/org/wildfly/security/auth/server/RegexNameValidatingRewriterTest.java
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1812 [ELY-2467] Update test cases in CipherSuiteSelectorTest to use a common helper method where appropriate
  ssl/src/test/java/org/wildfly/security/ssl/CipherSuiteSelectorTest.java
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1817 [ELY-2458] refactor digest string as HttpConstants.DIGEST_NAME
  auth/server/http/src/main/java/org/wildfly/security/auth/server/http/HttpAuthenticationFactory.java
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1820 [ELY-2478] WildFlyElytronClientDefaultSSLContextProvider configure method does not use constants
  auth/client/src/main/java/org/wildfly/security/auth/client/WildFlyElytronClientDefaultSSLContextProvider.java
Labels: +1 FJ, hacktoberfest-accepted

#1822 [ELY-2471] Make public static fields in Command class final
  tool/src/main/java/org/wildfly/security/tool/Command.java
Labels: +1 FJ, hacktoberfest-accepted

#1818 [ELY-2397]Update three test cases in DEREncoderTestCase to use a common helper method
  asn1/src/test/java/org/wildfly/security/asn1/DEREncoderTest.java
Labels: +1 FJ, hacktoberfest-accepted

#1823 ELY-2470 Extract the assignemt out of this expression
  auth/server/base/src/main/java/org/wildfly/security/auth/callback/CachedIdentityAuthorizeCallback.java
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1824 ELY-2472 Add Override annotation to FileSystemSecurityRealm methods
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1825 [ELY-2473] Move method getEntry from KeyStoreBackedSecurityRealm to its
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/KeyStoreBackedSecurityRealm.java
Labels: +1 FJ, +1 DV, hacktoberfest-accepted

#1826 [ELY-2481] Use assertNotEquals instead of using equals method in
  x500/cert/acme/src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
Labels: +1 FJ, hacktoberfest-accepted

#1827 [ELY-2466] Replace Collections.EMPTY_MAP with Collections.emptyMap()
  jose/util/src/main/java/org/wildfly/security/jose/util/SystemPropertiesJsonParserFactory.java
Labels: +1 FJ, hacktoberfest-accepted

#1828 [ELY-2474] Remove unnecessary boolean literal in LegacyPropertiesSecurityRealm
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
Labels: +1 FJ, hacktoberfest-accepted

#1830 Add a blog post about GHC22
  _posts/2022-10-31-ghc22-recap.adoc
  assets/images/posts/GHC22Panel.jpg
Labels: website
