Repository wildfly-security/wildfly-elytron, pull requests merged in 2022-06, with the labels that each got.

#1711 [ELY-2222] Add a test case for TLS where the client and server have different TLS protocols configured
  tests/base/src/test/java/org/wildfly/security/ssl/TLS13AuthenticationTest.java
  tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_5.xml
Labels: +1 FJ

#1718 EJBs over HTTPS: Securing Jakarta Enterprise Beans with mutual TLS authentication
  _data/authors.yaml
  _posts/2022-06-21-ejb-over-tls.adoc
Labels: +1 FJ, website

#1721 [ELY-2352] UpRev Jackson to 2.13.3
  pom.xml
Labels: +1 FJ

#1720 [ELY-2347] parseKeyStoreType crashes if type and wrap attributes not set
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/client/src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
  auth/client/src/test/resources/org/wildfly/security/auth/client/test-wildfly-config-v1_4.xml
Labels: +1 FJ

#1714 [ELY-2341] Added appropriate exclusions to the org.apache.httpcomponents:httpclient dependency in the pom.xml file.
  http/oidc/pom.xml
  pom.xml
Labels: +1 FJ

#1723 [ELY-2353] Add trace logging in org.wildfly.security.http.oidc.TokenValidator#parseAndVerifyToken
  http/oidc/src/main/java/org/wildfly/security/http/oidc/TokenValidator.java
Labels: +1 FJ, +1 DV
