Repository wildfly-security/wildfly-elytron, pull requests merged in 2022-09, with the labels that each got.

#1744 Add a blog post about bearer support for the Elytron OIDC Client subsystem
  _posts/2022-09-01-bearer-only-support-openid-connect.adoc
Labels: website

#1743 ELY-2390 Initialize empty keystore using load(null, null)
  keystore/src/main/java/org/wildfly/security/keystore/KeyStoreUtil.java
  tests/base/src/test/java/org/wildfly/security/ldap/KeyStoreSuiteChild.java
Labels: +1 FJ, +1 DV

#1745 Added navigation and guides for OSD 2022
  .gitignore
  OSD-2022.adoc
  _data/guides.yaml
  _data/navigation.yml
  _includes/OSD-2022-logo-bullets.html
  _includes/grid-icons.html
  _layouts/OSD-2022.html
  _layouts/community.html
  _layouts/default.html
  _layouts/guides.html
  _layouts/setup-elytron.html
  _sass/includes/highlighted-components.scss
  _sass/layouts/guides.scss
  _sass/main.scss
  assets/css/styles.scss
  assets/images/guides/icon-linux.png
  assets/images/guides/icon-macos.png
  assets/images/guides/icon-windows.png
  assets/images/icon-wildfly.png
  assets/images/setup-elytron/setup-elytron_fork-repo.png
  assets/images/setup-elytron/setup-elytron_github-clone.png
  assets/images/setup-elytron/setup-elytron_windows_env-vars.png
  assets/images/setup-elytron/setup-elytron_windows_install-jdk.png
  assets/images/setup-elytron/setup-elytron_windows_path-env-vars.png
  assets/javascript/highlight.pack.js
  getting-started-for-developers.adoc
  guides.adoc
  index.md
  setup-elytron-guides/restoring_configuration.adoc
  setup-elytron-guides/setup_elytron_linux.adoc
  setup-elytron-guides/setup_elytron_macos.adoc
  setup-elytron-guides/setup_elytron_windows.adoc
Labels: +1 DV

#1740 [ELY-2383] KeyStoreCredentialStoreTest fails in Windows without administrator privileges
  credential/store/src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
Labels: +1 FJ

#1758 [EL-2447] Added missing throw in Oidc#sendJsonHttpRequest
  http/oidc/src/main/java/org/wildfly/security/http/oidc/Oidc.java
Labels: +1 FJ, +1 DV

#1764 [ELY-2414] Add additional constructor to BearerMechanismFactory
  http/bearer/src/main/java/org/wildfly/security/http/bearer/BearerMechanismFactory.java
Labels: +1 FJ, +1 DV

#1762 ELY-2405:Use already defined constant X509_FORMAT instead of duplicating its value in FileSystemSecurityRealm#parseCertificate
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
Labels: +1 FJ, +1 DV

#1761 ELY-2450:Assign value to path in OidcCookieTokenStore#getContextPath
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcCookieTokenStore.java
Labels: +1 FJ, +1 DV

#1769 [ELY-2443] Extract the assignment from the return statement in Authen…
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
Labels: +1 FJ

#1768 ELY-2410:Remove unnecessary null check in ServerAuthenticationContext
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Labels: +1 FJ, +1 DV

#1763 [ELY-2444] Immediately return the value in SNISSLExplorer instead of …
  ssl/src/main/java/org/wildfly/security/ssl/SNISSLExplorer.java
Labels: +1 FJ, +1 DV

#1767 [ELY-2441] Moved assertion from test annotation to test body in DefaultSSLContextEmptyPathTest
  auth/client/src/test/java/org/wildfly/security/auth/client/DefaultSSLContextEmptyPathTest.java
Labels: +1 FJ, +1 DV

#1770 ELY-2437: Update DigestPasswordSpec to make use of MessageDigest#isEq…
  credential/base/src/main/java/org/wildfly/security/password/spec/DigestPasswordSpec.java
Labels: +1 FJ, +1 DV

#1772 ELY-2445: Fix the expected value and actual value order in RoleMappingsTest
  auth/server/base/src/test/java/org/wildfly/security/authz/RoleMappingTest.java
Labels: +1 FJ, +1 DV

#1771 ELY-2401 and ELY-2402:Make ENV_BINARY_ATTRIBUTES, NO_FILTER variable static
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
Labels: +1 FJ, +1 DV

#1774 [ELY-2442] Move the expected exception assertion from an annotation t…
  auth/client/src/test/java/org/wildfly/security/auth/client/DefaultSSLContextNonexistentConfigFileTest.java
Labels: +1 FJ, +1 DV

#1765 [ELY-2436] Update HashPasswordSpec to make use of MessageDigest#isEqual to avoid a potential timing attack
  credential/base/src/main/java/org/wildfly/security/password/spec/HashPasswordSpec.java
Labels: +1 FJ, +1 DV

#1773 ELY-2438: Update RawSimpleDigestPassword to make use of MessageDigest…
  credential/base/src/main/java/org/wildfly/security/password/interfaces/RawSimpleDigestPassword.java
Labels: +1 FJ, +1 DV

#1775 ELY-2435; ELY-2434; ELY-2433; ELY-2432
  credential/base/src/main/java/org/wildfly/security/password/interfaces/RawDigestPassword.java
  credential/base/src/main/java/org/wildfly/security/password/interfaces/RawSaltedSimpleDigestPassword.java
  credential/base/src/main/java/org/wildfly/security/password/interfaces/RawScramDigestPassword.java
  password/impl/src/main/java/org/wildfly/security/password/impl/UnixSHACryptPasswordImpl.java
Labels: +1 FJ, +1 DV

#1780 [ELY-2406] The error and status fields for the HttpFailure class shou…
  http/oidc/src/main/java/org/wildfly/security/http/oidc/ServerRequest.java
Labels: +1 FJ, +1 DV

#1783 [ELY-2400] Remove temporary variable assignment in Builder#addRealm
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
Labels: +1 FJ, +1 DV

#1782 [ELY-2399] Remove invalid assertion from SaslServerBuilder#setPlainText
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
Labels: +1 FJ, +1 DV

#1777 ELY-2409: Redundant static qualifier in AuthenticationError
  http/oidc/src/main/java/org/wildfly/security/http/oidc/AuthenticationError.java
Labels: +1 FJ, +1 DV

#1781 [ELY-2385] RawSecretKeyFactoryTest uses deprecated Assert.assertThat method
  credential/base/src/test/java/org/wildfly/security/key/RawSecretKeyFactoryTest.java
Labels: +1 FJ, +1 DV

#1776 [ELY-2419] Update GeneralName to make use of MessageDigest#isEqual to…
  x500/base/src/main/java/org/wildfly/security/x500/GeneralName.java
Labels: +1 FJ, +1 DV

#1785 [ELY-2408] Redundant static qualifier in HttpClientBuilder
  http/oidc/src/main/java/org/wildfly/security/http/oidc/HttpClientBuilder.java
Labels: +1 FJ, +1 DV

#1786 ELY 2421-ELY 2424 and ELY 2431
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
  password/impl/src/main/java/org/wildfly/security/password/impl/DigestPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/SaltedSimpleDigestPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/ScramDigestPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/SimpleDigestPasswordImpl.java
Labels: +1 FJ, +1 DV
