Repository wildfly-security/wildfly-elytron, pull requests merged in 2022-12, with the labels that each got.

#1810 [ELY-2468] Update getRealmIdentity so that it attempts to convert the given Principal to NamePrincipal if necessary
  auth/base/src/main/java/org/wildfly/security/auth/principal/NamePrincipal.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/JaasSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/KeyStoreBackedSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/SimpleMapBackedSecurityRealm.java
  auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/JdbcSecurityRealm.java
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
  tests/base/src/test/java/org/wildfly/security/auth/server/IdentityPropagationTest.java
Labels: INSUFFICIENT ACKS, +1 DV, Maintenance

#1850 [JBEAP-24221] [ELY-2117] SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate) on IBM JDK after ELY-2026
  ssl/src/main/java/org/wildfly/security/ssl/ConfiguredSSLServerSocketFactory.java
  ssl/src/main/java/org/wildfly/security/ssl/ConfiguredSSLSocketFactory.java
Labels: +1 FJ, +1 DV, Maintenance

#1809 [JBEAP-23946] CVE-2022-3143 wildfly-elytron: possible timing attacks via use of unsafe comparator
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
  credential/base/src/main/java/org/wildfly/security/credential/AbstractX509CertificateChainCredential.java
  credential/base/src/main/java/org/wildfly/security/password/interfaces/RawDigestPassword.java
  credential/base/src/main/java/org/wildfly/security/password/interfaces/RawSaltedSimpleDigestPassword.java
  credential/base/src/main/java/org/wildfly/security/password/interfaces/RawScramDigestPassword.java
  credential/base/src/main/java/org/wildfly/security/password/interfaces/RawSimpleDigestPassword.java
  credential/base/src/main/java/org/wildfly/security/password/spec/DigestPasswordSpec.java
  credential/base/src/main/java/org/wildfly/security/password/spec/HashPasswordSpec.java
  password/impl/src/main/java/org/wildfly/security/password/impl/DigestPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/MaskedPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/SaltedSimpleDigestPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/ScramDigestPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/SimpleDigestPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/SunUnixMD5CryptPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/UnixMD5CryptPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/UnixSHACryptPasswordImpl.java
  x500/base/src/main/java/org/wildfly/security/x500/GeneralName.java
Labels: INSUFFICIENT ACKS, Maintenance

#1852 [JBEAP-24248] [ELY-2492] Upgrade sshd-common from 2.7.0 to 2.9.2
  pom.xml
Labels: INSUFFICIENT ACKS, Maintenance

#1847 [ELY-2493] Upgrade jackson-databind to 2.13.4 to address CVE-2022-42004
  pom.xml
Labels: +1 FJ

#1797 [ELY-2317] Test case for static registration of WildFlyElytronClientDefaultSSLContextProvider
  auth/client/pom.xml
  auth/client/src/test/java/org/wildfly/security/auth/client/DefaultSSLContextProviderJavaSecurityStaticConfigurationTest.java
  auth/client/src/test/resources/org/wildfly/security/auth/client/java.security
Labels: +1 FJ, +1 DV

#1742 [ELY-2389] Consistent expression resolution with WildFly
  http/oidc/pom.xml
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcTest.java
  jose/util/src/main/java/org/wildfly/security/jose/util/SystemPropertiesJsonParserFactory.java
Labels: +1 DV
