Repository wildfly-security/wildfly-elytron, pull requests merged in 2023-10, with the labels that each got.

#1986 [ELY-2599] Update assertEquals calls in RegexRoleMapperTest so that t…
  auth/server/base/src/test/java/org/wildfly/security/authz/RegexRoleMapperTest.java
Labels: +1 DV

#1990 [ELY-2624] Update the JavaDoc for the PrincipalDecoder#aggregate method
  auth/server/base/src/main/java/org/wildfly/security/auth/server/PrincipalDecoder.java
Labels: +1 FJ

#1995 [ELY-2658] Remove the unassigned call to the constructor in X500Attri…
  tests/base/src/test/java/org/wildfly/security/x500/X500AttributePrincipalDecoderTest.java
Labels: +1 FJ

#2003 [ELY-2608] Adding MASK- prefix in a constant variable
  tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
Labels: +1 FJ, hacktoberfest-accepted

#2005 [ELY-2604] Make the constructor for FailoverRealmIdentity to “protected”
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FailoverSecurityRealm.java
Labels: +1 FJ, hacktoberfest-accepted

#2004 [ELY-2602] Update assertEquals calls in ElytronXmlParserTest so that the
  auth/client/src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
Labels: +1 FJ, hacktoberfest-accepted

#2000 [ELY-2412] Updated link to Elytron's Jira issues in README.adoc
  README.md
Labels: +1 FJ, hacktoberfest-accepted

#1999 [ELY-2613] Update an assertEquals call in ScramServerCompatibilityTest#testAllowedAuthorizationId so that the expected value and actual value are passed in the correct order
  tests/base/src/test/java/org/wildfly/security/sasl/scram/ScramServerCompatibilityTest.java
Labels: +1 FJ, hacktoberfest-accepted

#1997 [ELY-2621] Add a test that makes use of the RoleMapper#or method to R…
  auth/server/base/src/test/java/org/wildfly/security/authz/RoleMappingTest.java
Labels: rebase this, +1 FJ, +1 DV, hacktoberfest-accepted

#2002 [ELY-2612] removed duplicates in BasicScramSelfTest
  tests/base/src/test/java/org/wildfly/security/sasl/scram/BasicScramSelfTest.java
Labels: +1 FJ, hacktoberfest-accepted

#1991 [ELY-2622] Add a new test class that makes use of the BearerMechanismFactory
  http/bearer/pom.xml
  http/bearer/src/test/java/org/wildfly/security/http/bearer/BearerMechanismFactoryTest.java
Labels: +1 DV, hacktoberfest-accepted

#1993 [ELY-2615] Add a test class that tests creating and making use of a custom NameRewriter
  tests/base/src/test/java/org/wildfly/security/auth/server/CustomNameRewriterTest.java
Labels: +1 DV, hacktoberfest-accepted

#2006 [ELY-2614] Refactor KeyStoreUtilTest to use common method.
  keystore/src/test/java/org/wildfly/security/keystore/KeyStoreUtilTest.java
Labels: +1 DV, hacktoberfest-accepted

#1996 refactor: changes to close ELY-2595,2596,2597,2603,2605,2606,2607
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/main/java/org/wildfly/security/tool/ElytronTool.java
  tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
Labels: +1 DV, hacktoberfest-accepted

#2008 [ELY-2676] Merge if statement with the enclosing one in AcmeClientSpi…
  x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
Labels: +1 FJ, hacktoberfest-accepted

#2010 [ELY-2677] Merge if statement with the enclosing one in X500#createX5…
  x500/base/src/main/java/org/wildfly/security/x500/X500.java
Labels: +1 FJ, hacktoberfest-accepted

#2011 [ELY-2686] Merge an if statement with the enclosing one in X509EvidenceVerifier
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
Labels: hacktoberfest-accepted

#2009 [ELY-2685] Replace assert in PasswordBasedEncryptionUtilTest with a p…
  tests/base/src/test/java/org/wildfly/security/util/PasswordBasedEncryptionUtilTest.java
Labels: hacktoberfest-accepted

#2018 [ELY-2694] Update assertEquals calls in CommandCredentialSourceTest s…
  tests/base/src/test/java/org/wildfly/security/credential/source/impl/CommandCredentialSourceTest.java
Labels: +1 FJ, hacktoberfest-accepted

#2020 [ELY-2695] Update the import statement in CommandCredentialSourceTest…
  tests/base/src/test/java/org/wildfly/security/credential/source/impl/CommandCredentialSourceTest.java
Labels: +1 DV, hacktoberfest-accepted

#2019 [ELY-2690] Merge an if statement with the enclosing one in SSLUtils
  ssl/src/main/java/org/wildfly/security/ssl/SSLUtils.java
Labels: +1 DV, hacktoberfest-accepted

#2028 Add a blog post about GHC23 OSD recap
  _posts/2023-10-19-ghc23-osd-recap.adoc
  assets/images/posts/OpenSourceDay2023.png
Labels: website

#2024 [ELY-2691] Merge if statement with the enclosing one in X509RevocationT…
  ssl/src/main/java/org/wildfly/security/ssl/X509RevocationTrustManager.java
Labels: +1 FJ, hacktoberfest-accepted

#2022 [ELY-2692] - Merge an if statement with the enclosing one
  ssl/src/main/java/org/wildfly/security/ssl/X509RevocationTrustManager.java
Labels: +1 FJ, hacktoberfest-accepted

#2023 [ELY-2688] Merge an if statement with the enclosing one
  http/oidc/src/main/java/org/wildfly/security/http/oidc/RequestAuthenticator.java
Labels: +1 FJ, hacktoberfest-accepted

#2016 [ELY-2699] Update tests in DigestTest to call a common method in order to remove duplicated code
  tests/base/src/test/java/org/wildfly/security/sasl/digest/DigestTest.java
Labels: hacktoberfest-accepted

#2048 Fix commands in filesystem integrity blog
  _posts/2022-11-10-filesystem-integrity.adoc
Labels: website

#1927 [ELY-2576] Make it possible to use DigestPasswords when using the DIGEST-SHA-256 and DIGEST-SHA-512-256 HTTP Digest authentication mechanisms
  http/digest/src/main/java/org/wildfly/security/http/digest/DigestAuthenticationMechanism.java
  tests/base/src/test/java/org/wildfly/security/http/digest/DigestAuthenticationMechanismTest.java
  tests/base/src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
Labels: +1 DAL, +1 DV

#2025 [ELY-2687] - Merge an if statement with the enclosing one in ServerAuthen…
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Labels: +1 DV, hacktoberfest-accepted

#2027 [ELY-2682] Refactor OAuth2SaslClientV11Test to use common method
  tests/base/src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientV11Test.java
Labels: +1 DV, hacktoberfest-accepted

#2030 [ELY-2700] - Bump version.com.fasterxml.jackson from 2.15.2 to 2.15.3
  pom.xml
Labels: +1 DV, hacktoberfest-accepted

#2031 [ELY-2650] Upgrade sshd-common from 2.9.2 to 2.10.0
  pom.xml
Labels: +1 DV, hacktoberfest-accepted

#2032 [ELY-2660] Upgrade commons-cli:commons-cli from 1.4 to 1.5.0
  pom.xml
Labels: +1 DV, hacktoberfest-accepted

#2033 [ELY-2681] Refactor OAuth2SaslClientV10Test to use common method
  tests/base/src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientV10Test.java
Labels: +1 DV, hacktoberfest-accepted

#2035 [ELY-2679] Replace assert in VaultCommandTest with a proper check
  tool/src/test/java/org/wildfly/security/tool/VaultCommandTest.java
Labels: +1 DV, hacktoberfest-accepted

#2036 [ELY-2678] Replace assert in VaultCommandTest with a proper check
  tool/src/test/java/org/wildfly/security/tool/VaultCommandTest.java
Labels: +1 DV, hacktoberfest-accepted

#2038 [ELY-2672] Upgrade org.kohsuke.metainf-services:metainf-services from…
  pom.xml
Labels: +1 DV, hacktoberfest-accepted

#2039 [ELY-2671] Upgrade org.jboss.threads:jboss-threads from 2.4.0.Final t…
  pom.xml
Labels: +1 DV, hacktoberfest-accepted

#2042 [ELY-2693] Unit test code refactor (removed duplicates)
  tests/base/src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
Labels: +1 FJ, hacktoberfest-accepted

#2041 [ELY-2684] Unit test code refactor (removed duplicates)
  tests/base/src/test/java/org/wildfly/security/sasl/otp/OTPTest.java
Labels: +1 FJ, hacktoberfest-accepted

#2044 [ELY-2661] Upgrade jakarta.enterprise:jakarta.enterprise.cdi-api from 2.0.2 to 4.0.1
  pom.xml
Labels: +1 FJ, hacktoberfest-accepted

#2057 [ELY-2669] Upgrade org.jboss.modules:jboss-modules from 1.9.2.Final t…
  pom.xml
Labels: +1 DV, hacktoberfest-accepted

#2047 [ELY-2663] Upgrade org.apache.commons:commons-lang3 from 3.8.1 to 3.13.0
  pom.xml
Labels: +1 DV, hacktoberfest-accepted

#2045 [ELY-2673] Upgrade org.wildfly.common:wildfly-common
  pom.xml
Labels: +1 DV, hacktoberfest-accepted

#2051 [ELY-2667] Upgrade org.jboss.logging:jboss-logging from 3.4.3.Final to 3.5.3.Final
  pom.xml
Labels: +1 DV, hacktoberfest-accepted
