Repository wildfly-security/wildfly-elytron, pull requests merged in 2023-05, with the labels that each got.

#1886 Add blog post about DIGEST SHA algorithms configuration
  _posts/2023-05-15-specify-http-digest-algorithms.adoc
Labels: website

#1905 [ELY-2552] / [ELY-2554] Adjustments to mechanism selection and access the config selector.
  auth/server/base/src/main/java/org/wildfly/security/auth/server/AbstractMechanismAuthenticationFactory.java
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/HttpAuthenticationFactory.java
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/SaslAuthenticationFactory.java
  auth/server/http/src/main/java/org/wildfly/security/auth/server/http/HttpAuthenticationFactory.java
  auth/server/sasl/src/main/java/org/wildfly/security/auth/server/sasl/SaslAuthenticationFactory.java
  sasl/base/src/main/java/org/wildfly/security/sasl/util/SaslMechanismInformation.java
Labels: +1 DV

#1892 [ELY-2536] Tool encrypt command creates invalid CLI script for bulk conversion
  tool/src/main/java/org/wildfly/security/tool/FileSystemEncryptRealmCommand.java
  tool/src/test/java/org/wildfly/security/tool/FileSystemEncryptRealmCommandTest.java
  tool/src/test/resources/bulk-encryption-conversion-desc-without-names
Labels: +1 FJ, +1 DV

#1674 [ELY-2305] Add the ability to ignore unavailable realms for a distributed-realm
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/DistributedSecurityRealm.java
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/ElytronMessages.java
  tests/base/src/test/java/org/wildfly/security/auth/realm/DistributedSecurityRealmTest.java
Labels: +1 FJ, Feature Request, +1 DV

#1900 [ELY-1211] FileAuditEndpoint doesn't allow for file encoding to be overridden
  audit/src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java
  audit/src/main/java/org/wildfly/security/audit/SizeRotatingFileAuditEndpoint.java
  tests/base/src/test/java/org/wildfly/security/audit/FileAuditEndpointTest.java
Labels: +1 FJ, +1 DV

#1895 [ELY-2530/2542/2541/2546] Elytron Tool encrypt command fixes
  tool/mycredstore.cs
  tool/src/main/java/org/wildfly/security/tool/FileSystemEncryptRealmCommand.java
  tool/src/test/java/org/wildfly/security/tool/FileSystemEncryptRealmCommandTest.java
  tool/src/test/resources/bulk-encryption-conversion-desc
Labels: +1 DV

#1876 [ELY-2475] Use the primitive boolean expression in DelegatingAuthConfigFactory
  auth/jaspi/src/main/java/org/wildfly/security/auth/jaspi/DelegatingAuthConfigFactory.java
Labels: +1 DV

#1807 [ELY-2457] Swallowed exception in KeyStoreCredentialStore.flush
  credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
Labels: +1 DV

#1741 [ELY-2381] LdapSecurityRealm can return duplicated values for filtered attributes
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
  tests/base/src/test/java/org/wildfly/security/ldap/AbstractAttributeMappingSuiteChild.java
  tests/base/src/test/java/org/wildfly/security/ldap/GroupMappingSuiteChild.java
  tests/base/src/test/resources/ldap/elytron-group-mapping-tests.ldif
Labels: +1 DV

#1722 ELY-2354 remove IBM related changes due to unavailable security provi…
  auth/util/src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
  mechanism/gssapi/src/main/java/org/wildfly/security/mechanism/gssapi/GSSCredentialSecurityFactory.java
  tests/base/src/test/java/org/wildfly/security/auth/client/MaskedPasswordSSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/gssapi/JaasUtil.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLv2HelloAuthenticationTest.java
  tests/base/src/test/java/org/wildfly/security/ssl/TLS13AuthenticationTest.java
  tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
  tool/src/test/java/org/wildfly/security/tool/VaultCommandTest.java
  tool/src/test/resources/bulk-vault-conversion-desc-ibm
  tool/src/test/resources/vault-v1-more/vault-jceks-ibm.keystore
Labels: +1 DV

#1906 [ELY-2555] Upgrade net.minidev:json-smart to 2.4.9
  pom.xml
Labels: hold

#1908 [ELY-2559] Update CredentialStoreSaslAuthenticationTest
  tests/base/src/test/java/org/wildfly/security/auth/client/CredentialStoreSaslAuthenticationTest.java
Labels: +1 FJ

#1907 Ely-2558 Update assertions in OpenSSHKeyParserTest
  auth/client/src/test/java/org/wildfly/security/auth/client/OpenSSHKeysParserTest.java
Labels: +1 FJ
