Repository wildfly-security/wildfly-elytron, pull requests merged in 2023-02, with the labels that each got.

#1688 [ELY-2327] Add .gitleaks.toml file with allowlist
  .gitleaks.toml
Labels: +1 FJ

#1870 [ELY-2460] Add Override annotation to BCryptPassword#getParameterSpec
  credential/base/src/main/java/org/wildfly/security/password/interfaces/BCryptPassword.java
Labels: +1 DV

#1868 [ELY2459] Add override annotation to DigestPassword#getParameterSpec
  credential/base/src/main/java/org/wildfly/security/password/interfaces/DigestPassword.java
Labels: +1 DV

#1869 [ELY2461] Add override annotation to BSDUnixDESCryptPassword#getParam…
  credential/base/src/main/java/org/wildfly/security/password/interfaces/BSDUnixDESCryptPassword.java
Labels: +1 DV

#1872 [ELY-2520] Fix system property resolution in JSON files
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcTest.java
  jose/util/src/main/java/org/wildfly/security/jose/util/SystemPropertiesJsonParserFactory.java
Labels: +1 DAL, +1 DV

#1756 [ELY-2411] Add test cases to MappedRegexRealmMapperTest
  auth/util/src/test/java/org/wildfly/security/auth/util/MappedRegexRealmMapperTest.java
Labels: +1 DV

#1861 [ELY-2366] Add the missing @deprecated Javadoc tag to ElytronAuthenticator
  auth/client/src/main/java/org/wildfly/security/auth/util/ElytronAuthenticator.java
Labels: +1 DV

#1829 [ELY-2487] Misplaced invocation of isAutodetectedBearerOnly()
  http/oidc/src/main/java/org/wildfly/security/http/oidc/RequestAuthenticator.java
Labels: +1 FJ
