Repository wildfly-security/wildfly-elytron, pull requests merged in 2023-12, with the labels that each got.

#2052 [ELY-2668] Upgrade org.jboss.logmanager:jboss-logmanager from 2.1.18.Final to 2.1.19.Final
  pom.xml
Labels: +1 DV, hacktoberfest-accepted

#1940 [ELY-2577] OIDC testsuite relies on localhost being in /etc/hosts
  CONTRIBUTING.md
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcTest.java
Labels: +1 DV

#1702 ELY-2166: Added javadoc for org.wildfly.security.sasl.util.SaslMechanismInformation.Names class.
  sasl/base/src/main/java/org/wildfly/security/sasl/util/SaslMechanismInformation.java
Labels: +1 FJ, +1 DV

#1693 [ELY-2329] Utilize the simple implementation of HttpServerCookie
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcHttpFacade.java
  http/stateful-basic/src/main/java/org/wildfly/security/http/sfbasic/BasicAuthenticationMechanism.java
  tests/base/src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
Labels: +1 FJ, +1 DV

#1717 [ELY-2349] Clean up ElytronXmlParser code.
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
Labels: +1 FJ, +1 DV

#1712 [ELY-2167] Added javadoc for SNI realted classes. (SNIContextMatcher, SNISSLContext).
  ssl/src/main/java/org/wildfly/security/ssl/SNIContextMatcher.java
  ssl/src/main/java/org/wildfly/security/ssl/SNISSLContext.java
Labels: +1 DV
