Repository wildfly-security/wildfly-elytron, pull requests merged in 2023-01, with the labels that each got.

#1857 [ELY-2502] SASL authentication configured by the security command denies CLI connection
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/KeyStoreBackedSecurityRealm.java
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Labels: +1 FJ, +1 DV, Maintenance

#1843 [ELY-2182] LogManager warning when using the credential-store command
  tool/src/main/java/org/wildfly/security/tool/ElytronTool.java
Labels: +1 FJ, +1 DV

#1859 ELY-2505 upgrade to xnio 3.8.8.Final
  pom.xml
Labels: +1 FJ

#1629 [ELY-317] OneTimePassword transformer
  ELY_Messages.txt
  password/impl/src/main/java/org/wildfly/security/password/impl/ElytronMessages.java
  password/impl/src/main/java/org/wildfly/security/password/impl/OneTimePasswordImpl.java
  password/impl/src/test/java/org/wildfly/security/password/impl/OneTimePasswordTest.java
Labels: +1 FJ, +1 DV

#1862 [ELY-2509] Move HttpAuthenticator#isAuthenticated method to Authentic…
  http/base/src/main/java/org/wildfly/security/http/HttpAuthenticator.java
Labels: +1 DV
