Repository wildfly-security/wildfly-elytron, pull requests merged in 2024-01, with the labels that each got.

#1952 [ELY-2583] Make requestURI and Source-Address available from RealmSuccessfulAuthenticationEvent and RealmFailedAuthenticationEvent
  auth/server/base/src/main/java/org/wildfly/security/auth/callback/RequestInformationCallback.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
  http/util/src/main/java/org/wildfly/security/http/util/SetRequestInformationCallbackMechanismFactory.java
  tests/base/src/test/java/org/wildfly/security/auth/server/CustomRealm.java
  tests/base/src/test/java/org/wildfly/security/auth/server/RealmEventTest.java
Labels: Maintenance

#2078 [ELY-2710] Bump org.bitbucket.b_c:jose4j from 0.9.3 to 0.9.4
  pom.xml
Labels: +1 FJ

#2075 [ELY-2706] Upgrade commons-lang3 from 3.13.0 to 3.14.0
  pom.xml
Labels: +1 FJ

#2069 [ELY-2703] Upgrade Apache Commons CLI from 1.5.0 to 1.6.0
  pom.xml
Labels: +1 FJ

#2050 [ELY-2665] update org apache.httpcomponents.httpcore from 4.4.15 to 4.4.16
  pom.xml
Labels: +1 FJ, hacktoberfest-accepted

#1938 [ELY-2581] Update Elytron's SECURITY.md file
  SECURITY.md
Labels: +1 FJ
