Repository wildfly-security/wildfly-elytron, pull requests merged in 2024-02, with the labels that each got.

#2074 [ELY-2582] Upgrade Jackson FasterXML to version 2.15.2 - resolves CVE PRISMA-2023-0067
  pom.xml
Labels: +1 FJ, +1 DV

#1932 [ELY-2538] Caching realm should attempt to authenticate with underying realm if cached credential failed
  auth/realm/base/src/main/java/org/wildfly/security/auth/realm/CachingSecurityRealm.java
  tests/base/src/test/java/org/wildfly/security/auth/realm/cache/SecurityRealmIdentityCacheTest.java
Labels: +1 DAL, +1 FJ, Maintenance

#2094 [ELY-2589] Make sure the delegate#setAuthorized call happens before the super#setAuthorized call for SSO to ensure the session cache has the correct information after a session ID change
  http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnServerMechanismFactory.java
Labels: +1 DAL, +1 DV, Maintenance

#1922 [ELY-2557] Add an afterclass method to do clean-up after the FileSystemEncryptRealmCommandTest testBulkWithoutNames test
  tool/src/test/java/org/wildfly/security/tool/FileSystemEncryptRealmCommandTest.java
  tool/src/test/resources/bulk-encryption-conversion-desc-without-names
Labels: +1 IV

#2061 [ELY-2631] Add a test to SSLAuthenticationTest that tests the wantClientAuth option
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Labels: +1 DV, +1 IV

#2092 [ELY-2639] Add a test for MaskCommand.decryptMasked method
  tool/src/test/java/org/wildfly/security/tool/MaskCommandTest.java
Labels: +1 IV
