Repository wildfly-security/wildfly-elytron, pull requests merged in 2024-08, with the labels that each got.

#2148 [ELY-2765] cherry-picked ELY-2728 from branch 2.4.0.CR1
  tests/base/pom.xml
  wildfly-elytron/pom.xml
Labels: Maintenance

#2143 ELY-2756 Add tests to the elytron test suite to test to test OCSP with revoked and unknown certificates
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Labels: +1 FJ, +1 IV

#2181 Fixes to ELY-2756 Add tests to the elytron test suite to test to test OCSP with revoked and unknown certificates
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Labels: +1 FJ
