Repository wildfly-security/wildfly-elytron, pull requests merged in 2024-03, with the labels that each got.

#1939 [ELY-2580] Add new CVE Reporting page to the Elytron website
  _data/navigation.yml
  _layouts/security.html
  security.md
Labels: +1 FJ

#1708 [ELY-1815] Unable to set custom AUTHENTICATION_TIMEOUT value
  auth/server/sasl/src/main/java/org/wildfly/security/auth/server/sasl/SaslAuthenticationFactory.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslAuthenticationTimeoutTest.java
  tests/base/src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
Labels: +1 IV

#2096 [ELY-2715] Change log level for ELY23013 and ELY23012 to DEBUG
  http/oidc/src/main/java/org/wildfly/security/http/oidc/ElytronMessages.java
Labels: +1 DAL, +1 IV

#2076 [ELY-2708] Update the CONTRIBUTING.md file with information on Elytron's code review process and maintenance branches
  CONTRIBUTING.md
Labels: +1 DAL, +1 DV

#1981 [ELY-2591] Move min method into the PeriodicRotatingFileAuditEndpoint…
  audit/src/main/java/org/wildfly/security/audit/PeriodicRotatingFileAuditEndpoint.java
Labels: +1 DV

#2085 [ELY-2714] Attempting to read address data from an OIDC id token causes ClassCastException
  http/oidc/src/main/java/org/wildfly/security/http/oidc/IDToken.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/IDTokenTest.java
Labels: +1 DAL, +1 FJ

#2073 [JBEAP-26205] [ELY-2705] Update SecurityDomain#createAdHocIdentity so that it also calls SecurityDomain#transform to ensure that the security domain's security identity transformer gets used if configured
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
  auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
  tests/base/src/test/java/org/wildfly/security/auth/server/AdHocIdentityTest.java
Labels: INSUFFICIENT ACKS, +1 DV, Maintenance

#2106 [ELY-2728] Upgrade japicmp-maven-plugin to 0.20.0 so we can build with JDK 21
  tests/base/pom.xml
  wildfly-elytron/pom.xml
Labels: +1 DV

#2105 [ELY-2689] Update 3 tests in SunUnixMD5Crypt to call a common method in order to remove duplicated code
  password/impl/src/test/java/org/wildfly/security/password/impl/SunUnixMD5CryptTest.java
Labels: +1 FJ

#2107 [ELY-2319] Delete the deprecated GSSCredentialSecurityFactory implementation.
  auth/client/pom.xml
  auth/util/pom.xml
  auth/util/src/main/java/org/wildfly/security/auth/util/ElytronMessages.java
  auth/util/src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
  wildfly-elytron/pom.xml
Labels: +1 FJ

#2110 [ELY-2627] Changed array copy logic
  x500/base/src/main/java/org/wildfly/security/x500/util/X500PrincipalUtil.java
Labels: +1 DAL, +1 FJ

#2114 [ELY-2725] Update the modular.jdk.args used by the tests to get GssapiTestSuite passing with JDK 21
  tests/base/pom.xml
Labels: +1 DAL

#2013 ELY-2638 : Simplify test assertions in SSLAuthenticationTest
  tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Labels: +1 DAL, +1 FJ

#2112 ELY-2379 Rename a local variable in FileAuditEndpoint class [local_variable_renamed]
  audit/src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java
Labels: +1 FJ, +1 IV

#2116 [ELY-2726] Update AlternateSecurityManagerTest to be able to run with SE 21
  manager/base/src/test/java/org/wildfly/security/manager/AlternateSecurityManagerTest.java
Labels: +1 DAL, +1 FJ

#2117 [ELY-2545] referral-mode="ignore" and filter-base-dn=rootDN cause javax.naming.PartialResultException
  auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
Labels: +1 DAL

#1925 [ELY-2574] Add ability to configure additional scope for authentication request
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfigurationBuilder.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcJsonConfiguration.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcRequestAuthenticator.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/KeycloakConfiguration.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcBaseTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcTest.java
Labels: +1 DAL, +1 FJ

#1382 [ELY-1996] [Community] SSLContext to support delegation to alternate instances based on peer information.
  ELY_Messages.txt
  auth/client/pom.xml
  auth/client/src/main/java/org/wildfly/security/auth/client/ActiveSessionsSSLContext.java
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationContext.java
  auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java
  dynamic-ssl/pom.xml
  dynamic-ssl/src/main/java/org/wildfly/security/dynamic/ssl/DynamicSSLContext.java
  dynamic-ssl/src/main/java/org/wildfly/security/dynamic/ssl/DynamicSSLContextException.java
  dynamic-ssl/src/main/java/org/wildfly/security/dynamic/ssl/DynamicSSLContextImpl.java
  dynamic-ssl/src/main/java/org/wildfly/security/dynamic/ssl/DynamicSSLContextSPI.java
  dynamic-ssl/src/main/java/org/wildfly/security/dynamic/ssl/DynamicSSLContextSpiImpl.java
  dynamic-ssl/src/main/java/org/wildfly/security/dynamic/ssl/DynamicSSLSocketFactory.java
  dynamic-ssl/src/main/java/org/wildfly/security/dynamic/ssl/ElytronMessages.java
  dynamic-ssl/src/test/java/org/wildfly/security/dynamic/ssl/DynamicSSLContextTest.java
  dynamic-ssl/src/test/java/org/wildfly/security/dynamic/ssl/DynamicSSLTestUtils.java
  dynamic-ssl/src/test/java/org/wildfly/security/dynamic/ssl/SSLServerSocketTestInstance.java
  dynamic-ssl/src/test/resources/org/wildfly/security/dynamic/ssl/wildfly-config-dynamic-ssl-test-without-default-sslcontext.xml
  dynamic-ssl/src/test/resources/org/wildfly/security/dynamic/ssl/wildfly-config-dynamic-ssl-test.xml
  pom.xml
  tests/base/pom.xml
  wildfly-elytron/pom.xml
Labels: +1 DAL, +1 FJ, Feature Request

#1955 [ELY 2173] Add test for the CLIENT_CERT mechanism
  http/cert/pom.xml
  http/cert/src/test/java/org.wildfly.security.http.cert/ClientCertAuthenticationMechanismFactoryTest.java
  tests/base/pom.xml
  tests/base/src/test/java/org/wildfly/security/http/cert/ClientCertAuthenticationMechanismTest.java
  tests/base/src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
Labels: +1 DAL, +1 FJ
