Repository wildfly-security/wildfly-elytron, pull requests merged in 2024-10, with the labels that each got.

#2200 [ELY-2455]: Add a "FAQ for New Contributors" section to the CONTRIBUTING.md file (rebased from pr2091)"
  CONTRIBUTING.md
Labels: +1 DAL

#2214 [ELY-2850] Update DEREncoder#flush to use isEmpty() instead of size()
  asn1/src/main/java/org/wildfly/security/asn1/DEREncoder.java
Labels: +1 FJ, +1 IV

#2215 [ELY-2851] Update ElytronXmlParser#parseLocalKerberos to use isEmpty() instead of size()
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
Labels: +1 FJ, +1 IV

#2217 [ELY-2853] Return an expression directly instead of assigning it to a temporary variable
  auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateRealmEvidenceTest.java
Labels: +1 FJ, +1 IV

#2216 [ELY-2827] Replace wildcard imports with specific imports inside X509CertificateBuilderTest.java
  x500/cert/base/src/test/java/org/wildfly/security/x500/cert/X509CertificateBuilderTest.java
Labels: +1 FJ, +1 IV

#2219 [ELY-2826] Replace wildcard imports with specific imports inside OAuth2TokenSecurityRealmTest.java
  auth/realm/token/src/test/java/org/wildfly/security/auth/realm/token/OAuth2TokenSecurityRealmTest.java
Labels: +1 FJ, +1 IV

#2222 [ELY-2815] Renamed CA_JKS_LOCATION to CA_PKCS_LOCATION in TLS13AuthenticationTest
  tests/base/src/test/java/org/wildfly/security/ssl/TLS13AuthenticationTest.java
Labels: hacktoberfest-accepted, +1 IV

#2223 [ELY-2819] Fix the import order in OAuth2Client.java
  mechanism/oauth2/src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2Client.java
Labels: +1 FJ, hacktoberfest-accepted, +1 IV

#2226 [ELY-2849] upgrade the commons-io.commons-io dependency from 2.7 to 2…
  pom.xml
Labels: +1 FJ, hacktoberfest-accepted, +1 IV

#2227 [ELY-2825] Fix the import order for SetRequestInformationCallbackMechanismFactory.java
  http/util/src/main/java/org/wildfly/security/http/util/SetRequestInformationCallbackMechanismFactory.java
Labels: +1 FJ, hacktoberfest-accepted

#2228 [ELY-2828] Replace wildcard imports with specific imports inside X500PrincipalBuilderTest.java
  x500/base/src/test/java/org/wildfly/security/x500/X500PrincipalBuilderTest.java
Labels: +1 FJ, hacktoberfest-accepted, +1 IV

#2229 [ELY-2814] Update UnixSHACryptPasswordImpl to make use of MessageDigest.isEqual to avoid a potential timing attack
  password/impl/src/main/java/org/wildfly/security/password/impl/UnixSHACryptPasswordImpl.java
Labels: +1 FJ, hacktoberfest-accepted, +1 IV
