Repository wildfly-security/wildfly-elytron, pull requests merged in 2024-05, with the labels that each got.

#2142 [ELY-2727] Update CI to also run with JDK 21
  .github/workflows/pr-ci.yaml
Labels: +1 FJ, +1 IV

#1860 [ELY-489] Add JavaDoc for the 'org.wildfly.security.mechanism' package and sub packages
  mechanism/base/src/main/java/org/wildfly/security/mechanism/AuthenticationMechanismException.java
  mechanism/base/src/main/java/org/wildfly/security/mechanism/MechanismUtil.java
  mechanism/base/src/main/java/org/wildfly/security/mechanism/ScramServerErrorCode.java
  mechanism/base/src/main/java/org/wildfly/security/mechanism/ScramServerException.java
  mechanism/base/src/main/java/org/wildfly/security/mechanism/_private/MechanismUtil.java
  mechanism/digest/src/main/java/org/wildfly/security/mechanism/digest/DigestQuote.java
  mechanism/digest/src/main/java/org/wildfly/security/mechanism/digest/DigestUtil.java
  mechanism/digest/src/main/java/org/wildfly/security/mechanism/digest/PasswordDigestObtainer.java
  mechanism/gssapi/src/main/java/org/wildfly/security/mechanism/gssapi/GSSCredentialSecurityFactory.java
  mechanism/http/src/main/java/org/wildfly/security/mechanism/http/UsernamePasswordAuthenticationMechanism.java
  mechanism/oauth2/src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2Client.java
  mechanism/oauth2/src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2InitialClientMessage.java
  mechanism/oauth2/src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2Server.java
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramClient.java
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramFinalClientMessage.java
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramFinalServerMessage.java
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramInitialClientMessage.java
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramInitialServerMessage.java
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramInitialServerResult.java
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramMechanism.java
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramServer.java
  mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramUtil.java
Labels: +1 FJ, +1 IV

#2137 [ELY-2752] Ensure it's possible to make use of a custom principal-attribute value for OIDC
  http/oidc/src/main/java/org/wildfly/security/http/oidc/ElytronMessages.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/JsonWebToken.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcBaseTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcTest.java
Labels: +1 DAL, +1 IV

#2135 [ELY-2340] Add the ability to allow query params in redirect URIs via a new system property
  http/oidc/src/main/java/org/wildfly/security/http/oidc/Oidc.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcRequestAuthenticator.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/BearerTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcBaseTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/QueryParamsBaseTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/QueryParamsDisabledTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/QueryParamsEnabledTest.java
Labels: +1 DAL, +1 IV

#2136 [ELY-2340] Add the ability to allow query params in redirect URIs via a new system property
  http/oidc/src/main/java/org/wildfly/security/http/oidc/Oidc.java
  http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcRequestAuthenticator.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/BearerTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcBaseTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/QueryParamsBaseTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/QueryParamsDisabledTest.java
  http/oidc/src/test/java/org/wildfly/security/http/oidc/QueryParamsEnabledTest.java
Labels: Maintenance, +1 IV
