Repository wildfly-security/wildfly-elytron, pull requests merged in 2024-09, with the labels that each got.

#1713 [ELY-2082] Optimise Tool Help Text
  pom.xml
  tool/pom.xml
  tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
  tool/src/main/java/org/wildfly/security/tool/ElytronTool.java
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/main/java/org/wildfly/security/tool/FileSystemEncryptRealmCommand.java
  tool/src/main/java/org/wildfly/security/tool/FileSystemRealmCommand.java
  tool/src/main/java/org/wildfly/security/tool/FileSystemRealmIntegrityCommand.java
  tool/src/main/java/org/wildfly/security/tool/MaskCommand.java
  tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
  tool/src/main/java/org/wildfly/security/tool/help/CommandsSection.java
  tool/src/main/java/org/wildfly/security/tool/help/DescriptionSection.java
  tool/src/main/java/org/wildfly/security/tool/help/HelpCommand.java
  tool/src/main/java/org/wildfly/security/tool/help/HelpSection.java
  tool/src/main/java/org/wildfly/security/tool/help/OptionsSection.java
  tool/src/main/java/org/wildfly/security/tool/help/UsageSection.java
Labels: +1 FJ, +1 IV

#1916 [ELY-2547] Add Elytron Tool option to overwrite CLI script
  tool/src/main/java/org/wildfly/security/tool/Command.java
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/main/java/org/wildfly/security/tool/FileSystemEncryptRealmCommand.java
  tool/src/main/java/org/wildfly/security/tool/FileSystemRealmIntegrityCommand.java
  tool/src/test/java/org/wildfly/security/tool/FileSystemEncryptRealmCommandTest.java
  tool/src/test/java/org/wildfly/security/tool/FileSystemRealmIntegrityCommandTest.java
  tool/src/test/resources/filesystem-integrity/fs-unsigned-realms/fsRealmAl/a/l/alice-MFWGSY3F.xml
Labels: +1 IV

#2174 ELY-2794 Upgrade the keycloak-services and keycloak test dependencies to the latest version
  pom.xml
Labels: +1 FJ, +1 IV

#2111 [ELY-2662] Upgrade jakarta.json:jakarta.json-api from 2.0.0 to 2.1.2
  auth/realm/token/pom.xml
  http/oidc/pom.xml
  pom.xml
  tests/base/pom.xml
  tests/common/pom.xml
  x500/cert/acme/pom.xml
Labels: +1 DV

#2189 ELY-2731 Use SecureRandom instead of ThreadLocalRandom
  password/impl/src/main/java/org/wildfly/security/password/impl/BSDUnixDESCryptPasswordImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/PasswordUtil.java
  password/impl/src/main/java/org/wildfly/security/password/impl/ThreadLocalSecureRandom.java
  password/impl/src/main/java/org/wildfly/security/password/impl/UnixDESCryptPasswordImpl.java
  password/impl/src/test/java/org/wildfly/security/password/impl/PasswordUtilTest.java
Labels: +1 DAL, +1 IV

#2158 [ELY-2771] upgraded maven-javadoc-plugin to current version. Fixed b…
  pom.xml
Labels: +1 DAL, +1 FJ

#2159 [ELY-2770] update javadoc's @link stmt to display fully qualified cla…
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/HttpAuthenticationFactory.java
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/SaslAuthenticationFactory.java
  auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/SecurityIdentityServerMechanismFactory.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/CallbackHandlerCredentialSource.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/CommandCredentialSource.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/CredentialStoreCredentialSource.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/FactoryCredentialSource.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/KeyStoreCredentialSource.java
  credential/source/deprecated/src/main/java/org/wildfly/security/credential/source/LocalKerberosCredentialSource.java
  http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnServerMechanismFactory.java
  mechanism/base/src/main/java/org/wildfly/security/mechanism/MechanismUtil.java
  permission/src/main/java/org/wildfly/security/permission/PermissionActions.java
  sasl/base/src/main/java/org/wildfly/security/sasl/util/UsernamePasswordHashUtil.java
  sasl/deprecated/src/main/java/org/wildfly/security/sasl/util/AuthenticationContextSaslClient.java
  sasl/deprecated/src/main/java/org/wildfly/security/sasl/util/AuthenticationContextSaslClientFactory.java
  sasl/deprecated/src/main/java/org/wildfly/security/sasl/util/AuthenticationContextSaslServer.java
  sasl/deprecated/src/main/java/org/wildfly/security/sasl/util/AuthenticationContextSaslServerFactory.java
  ssl/src/main/java/org/wildfly/security/ssl/X509CRLExtendedTrustManager.java
  x500/deprecated/src/main/java/org/wildfly/security/x500/X500AttributePrincipalDecoder.java
Labels: +1 DAL, +1 FJ

#2175 [ELY-2704] Missing keystore password does not throw a meaningful exception
  auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
  auth/client/src/main/java/org/wildfly/security/auth/client/_private/ElytronMessages.java
Labels: +1 DAL, +1 IV

#2201 [ELY-2741] Enhance TRACE logging for the EXTERNAL HTTP mechanism
  http/external/src/main/java/org/wildfly/security/http/external/ExternalAuthenticationMechanism.java
  x500/cert/util/pom.xml
Labels: +1 DAL, +1 FJ

#2203 [ELY-2811] Add missing scope to dynamic-ssl pom.xml for wildfly-elytron-tests-common
  dynamic-ssl/pom.xml
Labels: +1 DAL

#2108 [ELY-2548] BasicAuthenticationMechanism should return FORBIDDEN instead of UNAUTHORIZED
  http/basic/src/main/java/org/wildfly/security/http/basic/BasicAuthenticationMechanism.java
  tests/base/src/test/java/org/wildfly/security/http/basic/BasicAuthenticationMechanismTest.java
  tests/base/src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
Labels: +1 DAL, +1 DV
