Repository wildfly-security/wildfly-elytron, pull requests merged in 2024-12, with the labels that each got.

#2242 [ELY-2865] Move CommandCredentialSourceTest to the wildfly-elytron-credential-source-impl module.
  credential/source/impl/pom.xml
  credential/source/impl/src/test/java/org/wildfly/security/credential/source/impl/CommandCredentialSourceTest.java
  credential/source/impl/src/test/java/org/wildfly/security/credential/source/impl/CredentialCommand.java
Labels: +1 FJ, +1 IV

#2233 [ELY-2831] Replace wildcard imports with specific imports inside PasswordFactorySpiImpl.java
  password/impl/src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java
Labels: +1 FJ, hacktoberfest-accepted

#2212 [ELY-2842] Upgrade the org.apache.directory.api dependency from versi…
  pom.xml
Labels: hacktoberfest-accepted

#2211 [ELY-2846] Update the link to the FAQ in the CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#2210 [ELY-2845] Upgrade the org.jboss.logging dependency from version 3.5.…
  pom.xml
Labels: hacktoberfest-accepted

#2209 [ELY-2844] Upgrade the org.apache.sshd.common dependency from version…
  pom.xml
Labels: hacktoberfest-accepted
