Repository wildfly-security/wildfly-elytron, pull requests merged in 2025-09, with the labels that each got.

#2293 [ELY-2922] If we are unable to obtain the SSLContext log the Exception at trace level.
  auth/client/src/main/java/org/wildfly/security/auth/client/WildFlyElytronClientDefaultSSLContextProvider.java
Labels: +1 DV, +1 IV

#2248 [ELY-2870] Add a new NamedGroup interface.
  auth/base/src/main/java/org/wildfly/security/auth/principal/NamedGroup.java
Labels: Jakarta_EE_11

#2194 [ELY-2547] Add Elytron Tool option to overwrite CLI script
  tool/src/main/java/org/wildfly/security/tool/Command.java
  tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
  tool/src/main/java/org/wildfly/security/tool/FileSystemEncryptRealmCommand.java
  tool/src/main/java/org/wildfly/security/tool/FileSystemRealmIntegrityCommand.java
  tool/src/test/java/org/wildfly/security/tool/FileSystemEncryptRealmCommandTest.java
  tool/src/test/java/org/wildfly/security/tool/FileSystemRealmIntegrityCommandTest.java
  tool/src/test/resources/filesystem-integrity/fs-unsigned-realms/fsRealmAl/a/l/alice-MFWGSY3F.xml
Labels: +1 DAL

#2205 [ELY-2377] RealmFailedAuthenticationEvent triggered during successful http programmatic login
  http/base/src/main/java/org/wildfly/security/http/HttpAuthenticator.java
  tests/base/src/test/java/org/wildfly/security/http/HttpAuthenticatorTest.java
  tests/base/src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
Labels: +1 DAL, +1 DV
